/* Infinite Realms 6 — cinematic client-only layer. Does not change Worker or game rules. */
'use strict';
(()=>{
 const game=document.getElementById('game');if(!game)return;
 const $=s=>game.querySelector(s),scene=$('.game-scene'),story=$('#game-story');if(!scene||!story)return;
 const KEY='infinite-realms-adventure6';let pref={};try{pref=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(pref))}catch{}};
 const bar=document.createElement('div');bar.className='a6-cinema-bar';bar.innerHTML='<span>✧ IMMERSIVE REALM</span><span class="a6-spacer"></span><button type="button" id="a6-intro-btn">✦ ورود سینمایی</button><button type="button" id="a6-full" aria-pressed="false">⛶ تمام‌صفحه</button><button type="button" id="a6-effects" aria-pressed="true">✧ جلوه‌ها</button>';$('.game-toolbar')?.after(bar);
 const compass=document.createElement('div');compass.className='a6-compass';compass.innerHTML='<span class="a6-star">✥</span><span id="a6-direction">سرزمین‌های ناشناخته</span>';scene.append(compass);
 const caption=document.createElement('div');caption.className='a6-scene-caption';caption.innerHTML='<strong id="a6-mood">در انتظار سرنوشت</strong><small id="a6-atmosphere">جهان تو در حال شکل‌گیری است</small>';scene.append(caption);
 const particles=document.createElement('div');particles.className='a6-particles';particles.setAttribute('aria-hidden','true');for(let i=0;i<20;i++){const p=document.createElement('i');p.style.cssText=`--x:${(i*47+13)%100}%;--y:${(i*29+11)%100}%;--s:${i%3+2}px;--d:${6+i%7}s;--delay:${-i*1.7}s`;particles.append(p)}scene.append(particles);
 const progress=document.createElement('div');progress.className='a6-story-progress';progress.innerHTML='<span id="a6-acts">◈ ماجراجویی هنوز آغاز نشده</span><div><i id="a6-progress"></i></div>';story.before(progress);
 const quick=document.createElement('div');quick.className='a6-quick';quick.setAttribute('aria-label','اقدام‌های سریع');quick.innerHTML='<button type="button" data-a6="observe">◈ بررسی</button><button type="button" data-a6="talk">♜ گفتگو</button><button type="button" data-a6="dice">⚄ D20</button><button type="button" data-a6="battle">⚔ نبرد</button><button type="button" data-a6="map">⌖ نقشه</button><button type="button" data-a6="bag">🎒 کوله</button>';$('.game-main')?.append(quick);
 const toast=document.createElement('div');toast.className='a6-toast';toast.setAttribute('role','status');document.body.append(toast);let toastTimeout;function announce(t){toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>toast.classList.remove('show'),3300)}
 const overlay=document.createElement('div');overlay.className='a6-overlay';overlay.hidden=true;overlay.innerHTML='<div class="a6-intro" role="dialog" aria-modal="true" aria-labelledby="a6-intro-title"><div class="a6-sigil">✥</div><small>INFINITE REALMS · YOUR STORY BEGINS</small><h2 id="a6-intro-title">دروازه قلمروها</h2><p id="a6-intro-text">هر انتخاب تو، سرنوشت این جهان را تغییر خواهد داد. شمشیرت را بردار؛ داستان آغاز می‌شود.</p><button type="button" id="a6-enter">ورود به ماجراجویی ⚔</button><p><small>برای خروج، کلید Esc را بزن</small></p></div>';game.append(overlay);
 let focusBefore=null;function intro(){focusBefore=document.activeElement;overlay.hidden=false;$('#a6-intro-text').textContent=($('#game-scene-desc')?.textContent||'هر انتخاب تو، سرنوشت این جهان را تغییر خواهد داد.').slice(0,260);$('#a6-enter').focus()}function closeIntro(){overlay.hidden=true;focusBefore?.focus?.()}$('#a6-intro-btn').onclick=intro;$('#a6-enter').onclick=()=>{closeIntro();$('#game-begin')?.click()};overlay.addEventListener('click',e=>{if(e.target===overlay)closeIntro()});
 const setFull=on=>{game.classList.toggle('a6-fullscreen',on);document.body.classList.toggle('a6-lock',on);$('#a6-full').setAttribute('aria-pressed',String(on));$('#a6-full').textContent=on?'⛶ خروج از تمام‌صفحه':'⛶ تمام‌صفحه';pref.full=on;save()};$('#a6-full').onclick=()=>setFull(!game.classList.contains('a6-fullscreen'));
 const effects=on=>{game.classList.toggle('a6-reduced',!on);particles.hidden=!on;$('#a6-effects').setAttribute('aria-pressed',String(on));$('#a6-effects').textContent=on?'✧ جلوه‌ها روشن':'✧ جلوه‌ها خاموش';pref.effects=on;save()};effects(pref.effects!==false);$('#a6-effects').onclick=()=>effects(game.classList.contains('a6-reduced'));
 const actions={observe:'به دقت محیط اطراف را بررسی می‌کنم؛ سرنخ‌ها و خطرات پنهان را توصیف کن.',talk:'با نزدیک‌ترین شخصیت حاضر گفتگو می‌کنم و درباره این مکان می‌پرسم.'};function send(t){const input=$('#game-input');if(!input)return;input.value=t;$('.adv-tabs [data-adv-tab="story"]')?.click();$('#game-form')?.requestSubmit()}
 quick.addEventListener('click',e=>{const b=e.target.closest('[data-a6]');if(!b)return;const action=b.dataset.a6;if(actions[action])send(actions[action]);if(action==='dice'){$('[data-roll="20"]')?.click();const die=$('#game-die');die?.classList.remove('a6-roll');void die?.offsetWidth;die?.classList.add('a6-roll');announce('⚄ '+($('#game-roll-result')?.textContent||'تاس D20 پرتاب شد'))}if(action==='battle')$('.adv-tabs [data-adv-tab="battle"]')?.click();if(action==='map')$('.adv-tabs [data-adv-tab="map"]')?.click();if(action==='bag')$('.adv-tabs [data-adv-tab="inventory"]')?.click()});
 let lastCount=-1;function sync(){const narrators=[...story.querySelectorAll('.game-narrator')],last=narrators.at(-1)?.querySelector('p')?.textContent||'',text=(last+' '+($('#game-scene-desc')?.textContent||'')).slice(0,2500),title=$('#game-scene-title')?.textContent||'قلمرو ناشناخته';scene.classList.remove('a6-storm','a6-tavern','a6-magic','a6-city');let mood='قلمرو اسرارآمیز',atmosphere='باد سرد · افسانه‌ای ناتمام';if(/طوفان|باران|رعد|storm|rain/i.test(text)){scene.classList.add('a6-storm');mood='طوفان در راه است';atmosphere='رعد و برق · آسمان تیره'}else if(/میخانه|مهمانخانه|کاروانسرا|tavern|inn/i.test(text)){scene.classList.add('a6-tavern');mood='آرامش پیش از ماجرا';atmosphere='نور شمع · زمزمه غریبه‌ها'}else if(/جادو|طلسم|پرتال|دروازه جادویی|magic|portal/i.test(text)){scene.classList.add('a6-magic');mood='نیرویی باستانی';atmosphere='جادوی ناشناخته · انرژی مرموز'}else if(/شهر|بازار|کوچه|city|market/i.test(text)){scene.classList.add('a6-city');mood='در قلب تمدن';atmosphere='همهمه شهر · رازهای پنهان'}else if(/نبرد|مبارزه|حمله|دشمن|battle/i.test(text)){mood='خطر نزدیک است';atmosphere='آماده نبرد شو'}else if(/جنگل|درخت|forest/i.test(text)){mood='جنگل ناشناخته';atmosphere='مه سرد · خش‌خش برگ‌ها'}else if(/غار|سیاهچال|قلعه|dungeon/i.test(text)){mood='در دل تاریکی';atmosphere='سنگ‌های کهن · پژواک قدم‌ها'}$('#a6-mood').textContent=mood;$('#a6-atmosphere').textContent=atmosphere;$('#a6-direction').textContent=title.slice(0,30);$('#a6-acts').textContent=narrators.length?'✧ '+narrators.length.toLocaleString('fa-IR')+' صحنه روایت‌شده':'◈ ماجراجویی هنوز آغاز نشده';$('#a6-progress').style.setProperty('--progress',Math.min(100,(narrators.length%10)*10)+'%');if(lastCount>=0&&narrators.length>lastCount&&lastCount>0)announce('✧ فصل تازه‌ای از ماجراجویی روایت شد');lastCount=narrators.length}
 new MutationObserver(sync).observe(story,{childList:true,subtree:true});$('#game-campaign')?.addEventListener('change',()=>setTimeout(sync,0));sync();
 document.addEventListener('keydown',e=>{if(!game.classList.contains('active'))return;if(e.key==='Escape'){if(!overlay.hidden)closeIntro();else if(game.classList.contains('a6-fullscreen'))setFull(false);return}if(e.target.closest('input,textarea,select,button,[contenteditable]')||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key.toLowerCase()==='f'){e.preventDefault();$('#a6-full').click()}if(e.key.toLowerCase()==='i'){e.preventDefault();intro()}if(e.key.toLowerCase()==='m'){$('.adv-tabs [data-adv-tab="map"]')?.click()}});
})();
