/* Infinite Realms 3.0 — interactive tactical encounter & inventory overlay. */
'use strict';
(()=>{
 const game=document.getElementById('game');if(!game)return;
 const $=s=>game.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const KEY='infinite-realms-adventure3';let data={};try{data=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};data.campaigns||={};
 const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(data))}catch{notify('فضای ذخیره مرورگر کافی نیست')}};
 const cid=()=>$('#game-campaign')?.value||'none';const current=()=>data.campaigns[cid()] ||= {encounter:{active:false,round:1,turn:0,actors:[],log:[]},items:[],gold:0};
 const random=n=>{const x=new Uint32Array(1);const limit=4294967296-(4294967296%n);do{crypto.getRandomValues(x)}while(x[0]>=limit);return x[0]%n+1};
 const notify=msg=>{const el=$('#game-feedback');if(el)el.textContent=msg};
 const tabs=$('.adv-tabs');if(!tabs)return;
 const combatTab=tabs.querySelector('[data-adv-tab="battle"]');if(combatTab)combatTab.textContent='⚔ نبرد زنده';
 const battle=$('#adv-battle');battle.innerHTML=`<div class="a3-heading"><span>⚔ میدان نبرد</span><span id="a3-round">راند ۱</span></div><p class="a3-hint">نبرد این بخش نوبتی و قابل مدیریت است. AI روایت می‌کند؛ آسیب و وضعیت فقط با اقدام شما تغییر می‌کنند.</p><div class="a3-tools"><button type="button" id="a3-start">✦ آغاز نبرد</button><button type="button" id="a3-next">نوبت بعدی ←</button><button type="button" id="a3-end">پایان نبرد</button></div><div class="a3-add"><label>نام دشمن<input id="a3-name" maxlength="45" placeholder="گابلین نگهبان"></label><label>جان<input id="a3-hp" type="number" min="1" max="9999" value="12"></label><label>زره<input id="a3-ac" type="number" min="1" max="40" value="12"></label><label>ابتکار<input id="a3-init" type="number" min="-20" max="50" value="10"></label><button type="button" id="a3-add">+ افزودن دشمن</button></div><div id="a3-actors" class="a3-actors"></div><div class="a3-dice"><button type="button" id="a3-attack">⚄ تاس حمله D20</button><label>اصلاح‌کننده<input id="a3-mod" type="number" min="-20" max="30" value="0"></label><label>آسیب<input id="a3-damage" type="number" min="0" max="9999" value="4"></label><button type="button" id="a3-hit">⚔ اعمال آسیب به هدف</button></div><p id="a3-result" role="status" class="a3-result">هدف را انتخاب کن، تاس بینداز و نتیجه را ثبت کن.</p><div class="a3-tools"><button type="button" id="a3-tell">✧ روایت نتیجه توسط DM</button><button type="button" id="a3-reset">↺ پاک‌کردن میدان</button></div><div id="a3-log" class="a3-log"></div>`;
 const invTab=document.createElement('button');invTab.type='button';invTab.className='adv-tab';invTab.dataset.advTab='inventory';invTab.setAttribute('aria-selected','false');invTab.textContent='🎒 کوله‌پشتی';tabs.append(invTab);
 const inventory=document.createElement('section');inventory.className='adv-panel a3-inventory';inventory.id='adv-inventory';inventory.hidden=true;inventory.innerHTML=`<div class="a3-heading"><span>🎒 کوله‌پشتی قهرمان</span><span>ذخیره خودکار</span></div><p class="a3-hint">وسایل و طلا را خودت ثبت و مدیریت کن. دریافت آیتم از متن AI هنوز خودکار نیست.</p><div class="a3-add"><label>نام آیتم<input id="a3-item-name" maxlength="70" placeholder="معجون درمان"></label><label>تعداد<input id="a3-item-count" type="number" min="1" max="999" value="1"></label><button type="button" id="a3-item-add">+ افزودن آیتم</button></div><div class="a3-gold"><label>🪙 طلای قهرمان <input id="a3-gold" type="number" min="0" max="99999999" value="0"></label></div><div id="a3-items" class="a3-items"></div>`;battle.after(inventory);
 // Wrap existing tab selection without altering earlier UI logic.
 tabs.addEventListener('click',e=>{const btn=e.target.closest('[data-adv-tab]');if(!btn)return;inventory.hidden=btn.dataset.advTab!=='inventory';if(btn.dataset.advTab==='inventory'){['dialogue','battle','journal'].forEach(id=>{$('#adv-'+id).hidden=true});$('#game-story').hidden=true;$('#game-choices').hidden=true;$('#game-form').hidden=true;tabs.querySelectorAll('[data-adv-tab]').forEach(t=>{t.classList.toggle('active',t===btn);t.setAttribute('aria-selected',String(t===btn))});renderItems()}},true);
 const enc=()=>current().encounter;let target=null,lastAttack=null;
 const log=t=>{const e=enc();e.log.unshift({text:t,time:Date.now()});e.log=e.log.slice(0,24);persist()};
 const actorId=()=>globalThis.crypto?.randomUUID?.()||'a'+Date.now()+Math.random().toString(36).slice(2);
 function renderBattle(){const e=enc();$('#a3-round').textContent=e.active?'راند '+e.round:'نبرد آغاز نشده';$('#a3-next').disabled=!e.active;$('#a3-actors').innerHTML=e.actors.length?e.actors.map((a,i)=>`<article class="a3-actor ${target===a.id?'selected':''} ${e.active&&e.turn===i?'current':''} ${a.hp<=0?'fallen':''}" data-id="${esc(a.id)}"><button type="button" class="a3-select" data-select="${esc(a.id)}"><strong>${e.active&&e.turn===i?'➤ ':''}${esc(a.name)}</strong><small>ابتکار ${a.init} · AC ${a.ac}</small><span class="a3-hpbar"><i style="width:${Math.max(0,Math.min(100,a.hp/a.max*100))}%"></i></span><small>♥ ${a.hp} / ${a.max} ${target===a.id?'· هدف':''}</small></button><div class="a3-actor-actions"><button type="button" data-heal="${esc(a.id)}">+۵ جان</button><button type="button" data-remove="${esc(a.id)}">حذف</button></div></article>`).join(''):'<p class="a3-empty">هنوز مبارزی در میدان نیست. دشمن اضافه کن یا نبرد را آغاز کن.</p>';$('#a3-log').innerHTML=e.log.map(l=>`<p><small>${new Date(l.time).toLocaleTimeString('fa-IR')}</small> ${esc(l.text)}</p>`).join('')}
 function renderItems(){const s=current();$('#a3-gold').value=s.gold||0;$('#a3-items').innerHTML=s.items.length?s.items.map(item=>`<article><strong>${esc(item.name)}</strong><span>× ${item.count}</span><div><button type="button" data-use="${esc(item.id)}">مصرف / کم‌کردن</button><button type="button" data-delete="${esc(item.id)}">حذف</button></div></article>`).join(''):'<p class="a3-empty">کوله‌پشتی خالی است.</p>'}
 $('#a3-add').onclick=()=>{const name=$('#a3-name').value.trim();const hp=Number($('#a3-hp').value),ac=Number($('#a3-ac').value),init=Number($('#a3-init').value);if(!name||!Number.isInteger(hp)||hp<1||hp>9999||!Number.isInteger(ac)||ac<1||ac>40||!Number.isInteger(init)||init< -20||init>50)return notify('نام، جان، زره و ابتکار معتبر وارد کن.');enc().actors.push({id:actorId(),name,hp,max:hp,ac,init});log('دشمن «'+name+'» وارد میدان شد.');$('#a3-name').value='';renderBattle()};
 $('#a3-start').onclick=()=>{const e=enc();if(e.active)return notify('نبرد در جریان است.');const hero=$('#game-hero')?.selectedOptions?.[0]?.textContent?.split(' · ')[0]||'قهرمان';const hcard=$('#game-hero-card')?.textContent||'';const hp=Number(hcard.match(/(\d+)\s*HP/i)?.[1]||10),ac=Number(hcard.match(/(\d+)\s*AC/i)?.[1]||12);if(!e.actors.some(a=>a.hero)){e.actors.push({id:actorId(),name:hero,hp,max:hp,ac,init:random(20),hero:true})}e.actors.sort((a,b)=>b.init-a.init);e.round=1;e.turn=0;e.active=true;log('نبرد آغاز شد؛ نوبت '+e.actors[0].name);renderBattle()};
 $('#a3-next').onclick=()=>{const e=enc();if(!e.active||!e.actors.length)return;let i=e.turn;for(let k=0;k<e.actors.length;k++){i=(i+1)%e.actors.length;if(i===0)e.round++;if(e.actors[i].hp>0)break}e.turn=i;log('نوبت '+e.actors[i].name+' · راند '+e.round);renderBattle()};
 $('#a3-end').onclick=()=>{enc().active=false;log('نبرد پایان یافت.');renderBattle()};
 $('#a3-actors').onclick=e=>{const b=e.target.closest('button');if(!b)return;const x=enc().actors.find(a=>a.id===(b.dataset.select||b.dataset.heal||b.dataset.remove));if(!x)return;if(b.dataset.select){target=x.id;$('#a3-result').textContent='هدف: '+x.name+' · AC '+x.ac}else if(b.dataset.heal){x.hp=Math.min(x.max,x.hp+5);log(x.name+' پنج جان بازیابی کرد.')}else if(b.dataset.remove){enc().actors=enc().actors.filter(a=>a!==x);enc().turn=0;if(target===x.id)target=null;log(x.name+' از میدان حذف شد.')}persist();renderBattle()};
 $('#a3-attack').onclick=()=>{const v=random(20),mod=Math.max(-20,Math.min(30,Number($('#a3-mod').value)||0)),a=enc().actors.find(x=>x.id===target);lastAttack={roll:v,total:v+mod,target:target,hit:a? v===20||(v!==1&&v+mod>=a.ac):null};$('#a3-result').textContent=`⚄ D20: ${v} ${mod>=0?'+':''}${mod} = ${v+mod}${a?' · '+(lastAttack.hit?'اصابت به '+a.name:'عدم اصابت به '+a.name):' · هدفی انتخاب نشده'}`;log('تاس حمله: '+v+' + '+mod+' = '+(v+mod)+(a?' علیه '+a.name:''));renderBattle()};
 $('#a3-hit').onclick=()=>{const a=enc().actors.find(x=>x.id===target),damage=Number($('#a3-damage').value);if(!a)return notify('اول یک هدف انتخاب کن.');if(!Number.isInteger(damage)||damage<0||damage>9999)return notify('مقدار آسیب نامعتبر است.');if(lastAttack&&lastAttack.target===a.id&&!lastAttack.hit)return notify('حمله قبلی به هدف اصابت نکرد. برای اعمال آسیب مستقیم، هدف را دوباره انتخاب کن.');a.hp=Math.max(0,a.hp-damage);log(a.name+' '+damage+' آسیب دید'+(a.hp===0?' و از پا افتاد.':'.'));$('#a3-result').textContent='⚔ '+a.name+': '+a.hp+' / '+a.max+' HP';lastAttack=null;persist();renderBattle()};
 $('#a3-tell').onclick=()=>{const e=enc();if(!e.log.length)return notify('اول نبرد را آغاز کن.');const msg='در ادامه داستان، نتیجه این اتفاقات نبرد را روایت کن؛ بدون جعل تاس یا تغییر خودکار جان: '+e.log.slice(0,6).reverse().map(x=>x.text).join(' | ');const input=$('#game-input');input.value=msg;tabs.querySelector('[data-adv-tab="story"]')?.click();$('#game-form').requestSubmit()};
 $('#a3-reset').onclick=()=>{if(!confirm('تمام وضعیت میدان این کمپین پاک شود؟'))return;current().encounter={active:false,round:1,turn:0,actors:[],log:[]};target=null;lastAttack=null;persist();renderBattle()};
 $('#a3-item-add').onclick=()=>{const name=$('#a3-item-name').value.trim(),count=Number($('#a3-item-count').value);if(!name||!Number.isInteger(count)||count<1||count>999)return notify('نام و تعداد معتبر وارد کن.');const items=current().items;const old=items.find(i=>i.name===name);if(old)old.count+=count;else items.push({id:actorId(),name,count});$('#a3-item-name').value='';persist();renderItems()};
 $('#a3-items').onclick=e=>{const b=e.target.closest('button');if(!b)return;const s=current(),item=s.items.find(i=>i.id===(b.dataset.use||b.dataset.delete));if(!item)return;if(b.dataset.use)item.count--;else if(b.dataset.delete&&!confirm('این آیتم حذف شود؟'))return;if(item.count<=0||b.dataset.delete)s.items=s.items.filter(i=>i!==item);persist();renderItems()};
 $('#a3-gold').onchange=()=>{current().gold=Math.max(0,Math.min(99999999,Math.floor(Number($('#a3-gold').value)||0)));persist();renderItems()};
 $('#game-campaign').addEventListener('change',()=>{target=null;lastAttack=null;renderBattle();renderItems()});renderBattle();renderItems();
})();
