/* Infinite Realms Adventure Mode 2.0 — UI layer, no backend changes. */
'use strict';
(()=>{
const game=document.getElementById('game');if(!game)return;
const $=s=>game.querySelector(s), safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='infinite-realms-adventure2';let settings={};try{settings=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};
const save=()=>localStorage.setItem(KEY,JSON.stringify(settings));
const main=$('.game-main'), scene=$('.game-scene'), story=$('#game-story'), form=$('#game-form');
const top=document.createElement('div');top.className='adv-topline';top.innerHTML='<span class="adv-live"><i></i> ADVENTURE MODE</span><span id="adv-location">◈ قلمرو ناشناخته</span><span id="adv-time">☾ ماجراجویی ادامه دارد</span>';scene.prepend(top);
const hud=document.createElement('div');hud.className='adv-hero-hud';hud.innerHTML='<div class="adv-hero-name" id="adv-name">قهرمان ناشناس</div><div class="adv-hp-label"><span>♥ جان قهرمان</span><strong id="adv-hp-text">—</strong></div><div class="adv-hp-track"><div id="adv-hp-fill"></div></div><div class="adv-hud-stats"><span id="adv-level">سطح —</span><span id="adv-ac">⛨ AC —</span></div>';scene.append(hud);
const nav=document.createElement('div');nav.className='adv-tabs';nav.setAttribute('role','tablist');nav.innerHTML='<button type="button" class="adv-tab active" data-adv-tab="story" aria-selected="true">✦ ماجراجویی</button><button type="button" class="adv-tab" data-adv-tab="dialogue" aria-selected="false">♜ گفتگو</button><button type="button" class="adv-tab" data-adv-tab="battle" aria-selected="false">⚔ مبارزه</button><button type="button" class="adv-tab" data-adv-tab="journal" aria-selected="false">☷ دفتر وقایع</button>';scene.after(nav);
const stage=document.createElement('section');stage.className='adv-stage';stage.innerHTML=`<div id="adv-dialogue" class="adv-panel" hidden><div class="adv-panel-head"><span class="adv-emblem">♜</span><div><small>گفتگوی تعاملی</small><h3 id="adv-npc">شخصیت‌های داستان</h3></div></div><p id="adv-npc-text">برای شروع گفتگو، از DM بخواه با یکی از شخصیت‌های صحنه صحبت کنی.</p><div class="adv-actions"><button type="button" data-adv-action="با نزدیک‌ترین شخصیت حاضر گفتگو می‌کنم؛ نام و ظاهرش را توصیف کن و از او درباره این مکان می‌پرسم.">شروع گفتگو</button><button type="button" data-adv-action="سعی می‌کنم با متقاعدسازی اطلاعات بیشتری از این شخصیت به دست بیاورم. اگر آزمون لازم است، DC را بگو.">متقاعدسازی</button><button type="button" data-adv-action="با دقت به لحن و رفتار این شخصیت توجه می‌کنم تا نیت او را تشخیص دهم. اگر آزمون لازم است، DC را بگو.">تشخیص نیت</button></div></div><div id="adv-battle" class="adv-panel" hidden><div class="adv-panel-head"><span class="adv-emblem">⚔</span><div><small>حالت نبرد</small><h3>برای نبرد آماده‌ای؟</h3></div></div><p id="adv-battle-note">این بخش فرمان‌های نبرد را به DM می‌فرستد. نتیجه حمله و آسیب فقط پس از تاس و تأیید قوانین مشخص می‌شود.</p><div class="adv-actions"><button type="button" data-adv-action="آماده حمله می‌شوم؛ دشمنان حاضر، ترتیب نوبت‌ها و نوع تاس موردنیاز برای حمله را مشخص کن.">⚔ حمله</button><button type="button" data-adv-action="در موضع دفاعی قرار می‌گیرم. بر اساس قوانین موجود نتیجه دفاع را مشخص کن.">⛨ دفاع</button><button type="button" data-adv-action="می‌خواهم از جادوی مناسب شخصیت خودم استفاده کنم؛ گزینه‌های ممکن و هزینه هرکدام را بگو.">✧ جادو</button><button type="button" data-adv-action="سعی می‌کنم از نبرد عقب‌نشینی کنم. موانع و آزمون‌های لازم را مشخص کن.">➤ عقب‌نشینی</button></div><div class="adv-battle-tools"><button type="button" id="adv-roll">⚄ پرتاب D20</button><button type="button" id="adv-send-roll">اعلام تاس به DM</button><button type="button" id="adv-open-combat">نمایش ردیاب مبارزه</button></div></div><div id="adv-journal" class="adv-panel" hidden><div class="adv-panel-head"><span class="adv-emblem">☷</span><div><small>تاریخچه ماجراجویی</small><h3>دفتر وقایع</h3></div></div><div id="adv-journal-list" class="adv-journal-list">هنوز رویدادی ثبت نشده است.</div><button type="button" id="adv-backup">↓ دانلود پشتیبان کمپین</button></div>`;
nav.after(stage);
const toast=msg=>{const el=$('#game-feedback');if(el)el.textContent=msg};
function selectTab(name){nav.querySelectorAll('[data-adv-tab]').forEach(b=>{const active=b.dataset.advTab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});['dialogue','battle','journal'].forEach(id=>{const p=$('#adv-'+id);p.hidden=id!==name});story.hidden=name!=='story';$('#game-choices').hidden=name!=='story';form.hidden=name==='journal';settings.tab=name;save()}
nav.addEventListener('click',e=>{const b=e.target.closest('[data-adv-tab]');if(b)selectTab(b.dataset.advTab)});
function act(text){const input=$('#game-input');if(!input)return;input.value=text;form.requestSubmit()}
stage.addEventListener('click',e=>{const b=e.target.closest('[data-adv-action]');if(b)act(b.dataset.advAction)});
$('#adv-roll').onclick=()=>{$('[data-roll="20"]')?.click();$('#adv-battle-note').textContent=$('#game-roll-result')?.textContent||'تاس پرتاب شد'};
$('#adv-send-roll').onclick=()=>$('#game-send-roll')?.click();
$('#adv-open-combat').onclick=()=>document.querySelector('#nav [data-page="combat"]')?.click();
$('#adv-backup').onclick=()=>$('#game-export')?.click();
function sync(){const text=$('#game-hero-card')?.textContent||'';const h=$('#game-hero')?.selectedOptions?.[0]?.textContent||'';$('#adv-name').textContent=h.split(' · ')[0]||'قهرمان ناشناس';const hp=text.match(/(\d+)\s*HP/i),lvl=text.match(/سطح\s*(\d+)/),ac=text.match(/(\d+)\s*AC/i);$('#adv-hp-text').textContent=hp?hp[1]+' HP':'—';$('#adv-hp-fill').style.width=hp?Math.min(100,Math.max(0,Number(hp[1])/Math.max(10,Number(hp[1]))*100))+'%':'0%';$('#adv-level').textContent='سطح '+(lvl?.[1]||'—');$('#adv-ac').textContent='⛨ AC '+(ac?.[1]||'—');$('#adv-location').textContent='◈ '+($('#game-scene-title')?.textContent||'قلمرو ناشناخته');const entries=[...story.querySelectorAll('.game-narrator')];const last=entries.at(-1)?.querySelector('p')?.textContent||'';const npc=last.match(/(?:«([^»]{2,40})»|(?:نام(?:ش)?|به نام)\s+([^،.\n]{2,35}))/);$('#adv-npc').textContent=npc?.[1]||npc?.[2]||'شخصیت‌های داستان';$('#adv-npc-text').textContent=last.slice(0,340)||'برای گفتگو با یکی از شخصیت‌های داستان، گزینه شروع گفتگو را انتخاب کن.';$('#adv-journal-list').innerHTML=entries.length?entries.slice(-12).reverse().map((x,i)=>`<article><small>رویداد ${entries.length-i}</small><p>${safe(x.querySelector('p')?.textContent?.slice(0,600)||'')}</p></article>`).join(''):'هنوز رویدادی ثبت نشده است.';const battle=/نبرد|مبارزه|حمله|دشمن|شمشیر|اژدها|جنگ/i.test(last);game.classList.toggle('adv-in-battle',battle);$('#adv-time').textContent=battle?'⚔ احتمال رویارویی':'☾ ماجراجویی ادامه دارد'}
const observer=new MutationObserver(sync);observer.observe(story,{childList:true,subtree:true});observer.observe($('#game-hero-card'),{childList:true,subtree:true});$('#game-hero').addEventListener('change',()=>setTimeout(sync,0));$('#game-campaign').addEventListener('change',()=>setTimeout(sync,0));sync();selectTab(['story','dialogue','battle','journal'].includes(settings.tab)?settings.tab:'story');
})();
