/* Adventure 8 — mobile-first contextual controller. No backend changes. */
'use strict';(()=>{const game=document.getElementById('game');if(!game)return;const $=s=>game.querySelector(s),tab=n=>$('.adv-tabs [data-adv-tab="'+n+'"]')?.click();const toolbar=$('.game-toolbar'),main=$('.game-main'),scene=$('.game-scene');if(!toolbar||!main||!scene)return;
const setup=document.createElement('div');setup.className='a8-setup';setup.hidden=true;toolbar.before(setup);setup.append(toolbar);
const context=document.createElement('div');context.className='a8-context';context.innerHTML='<div><strong id="a8-mode">✦ ماجراجویی</strong><br><span id="a8-tip">یک انتخاب انجام بده یا اقدام دلخواهت را بنویس.</span></div><button type="button" class="a8-desktop-toggle" id="a8-settings" aria-expanded="false">⚙ تنظیمات</button>';scene.after(context);
const dock=document.createElement('nav');dock.className='a8-dock';dock.setAttribute('aria-label','دسترسی سریع بازی');dock.innerHTML='<button type="button" data-a8="story" class="a8-primary">✦ داستان</button><button type="button" data-a8="battle">⚔ نبرد</button><button type="button" data-a8="dice">⚄ تاس</button><button type="button" data-a8="map">⌖ نقشه</button><button type="button" data-a8="more">☰ بیشتر</button>';main.append(dock);
const scrim=document.createElement('div');scrim.className='a8-scrim';scrim.hidden=true;const sheet=document.createElement('div');sheet.className='a8-sheet';sheet.hidden=true;sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');sheet.setAttribute('aria-label','اقدام‌های بیشتر');sheet.innerHTML='<div class="a8-sheet-header"><h3 id="a8-sheet-title">دسترسی سریع</h3><button type="button" class="a8-close" id="a8-close">✕ بستن</button></div><div class="a8-sheet-actions" id="a8-sheet-actions"></div><p class="a8-hint" id="a8-sheet-hint">ابزارهای مرتبط با موقعیت فعلی اینجا ظاهر می‌شوند.</p>';game.append(scrim,sheet);
let focusBefore=null;function close(){sheet.hidden=true;scrim.hidden=true;focusBefore?.focus?.()}function open(title,actions,hint){focusBefore=document.activeElement;$('#a8-sheet-title').textContent=title;$('#a8-sheet-actions').replaceChildren();for(const [label,action] of actions){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>{close();action()});$('#a8-sheet-actions').append(b)}$('#a8-sheet-hint').textContent=hint||'';sheet.hidden=false;scrim.hidden=false;$('#a8-close').focus()}$('#a8-close').onclick=close;scrim.onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!sheet.hidden)close()});
const send=t=>{tab('story');const input=$('#game-input');if(input){input.value=t;$('#game-form')?.requestSubmit()}};const showTab=n=>{tab(n);$('.adv-stage')?.scrollIntoView({behavior:'smooth',block:'start'})};const roll=n=>{$('[data-roll="'+n+'"]')?.click();open('⚄ نتیجه تاس', [['اعلام نتیجه به DM',()=>$('#game-send-roll')?.click()],['تاس دوباره',()=>roll(n)],['برگشت به بازی',()=>tab('story')]],$('#game-roll-result')?.textContent||'تاس پرتاب شد')};
function more(){open('☰ ابزارهای ماجراجویی', [['🎒 کوله‌پشتی',()=>showTab('inventory')],['♜ گفتگو',()=>showTab('dialogue')],['☷ دفتر وقایع',()=>showTab('journal')],['♟ شخصیت‌های جهان',()=>showTab('npcs')],['✧ مهارت‌ها و جادو',()=>showTab('rules')],['⚙ کمپین و قهرمان',()=>{setup.hidden=false;$('#a8-settings').setAttribute('aria-expanded','true');setup.scrollIntoView({behavior:'smooth'})}],['☁ بازیابی ابری',()=>$('#game-sync')?.click()],['↓ پشتیبان',()=>$('#game-export')?.click()]],'امکانات قبلی حذف نشده‌اند؛ همه از اینجا در دسترس‌اند.')}
function dice(){open('⚄ تاس سرنوشت',[4,6,8,10,12,20].map(n=>['D'+n,()=>roll(n)]),'برای آزمون مهارت معمولاً D20 استفاده می‌شود.')}
function battle(){showTab('battle');open('⚔ نوبت مبارزه',[['⚔ حمله',()=>$('#a3-attack')?.click()],['⛨ دفاع',()=>send('در موضع دفاعی قرار می‌گیرم؛ نتیجه را بر اساس قوانین توضیح بده.')],['✧ جادو',()=>send('می‌خواهم از جادوی در دسترس شخصیت استفاده کنم؛ گزینه‌ها و هزینه‌ها را بگو.')],['⚄ تاس D20',()=>roll(20)],['🎯 میدان نبرد',()=>showTab('battle')]],'در میدان نبرد هدف و زره را انتخاب کن؛ نتیجه آسیب باید ثبت شود.')}
dock.onclick=e=>{const b=e.target.closest('[data-a8]');if(!b)return;const a=b.dataset.a8;if(a==='story')showTab('story');if(a==='battle')battle();if(a==='dice')dice();if(a==='map')showTab('map');if(a==='more')more()};$('#a8-settings').onclick=()=>{setup.hidden=!setup.hidden;$('#a8-settings').setAttribute('aria-expanded',String(!setup.hidden))};
let last='';function sync(){const text=[...game.querySelectorAll('#game-story .game-narrator p')].at(-1)?.textContent||'';if(text===last)return;last=text;const mode=/نبرد|حمله|مبارزه|دشمن|اژدها|جنگ/i.test(text)?'battle':/گفتگو|صحبت|پرسید|میخانه|بازرگان|نگهبان/i.test(text)?'dialogue':/سفر|نقشه|جاده|حرکت|روستا|شهر/i.test(text)?'map':'story';$('#a8-mode').textContent=({battle:'⚔ موقعیت نبرد',dialogue:'♜ موقعیت گفتگو',map:'⌖ سفر و اکتشاف',story:'✦ ماجراجویی'})[mode];$('#a8-tip').textContent=({battle:'حمله، دفاع یا تاس؛ همه در دسترس‌اند.',dialogue:'با شخصیت‌ها گفتگو کن یا نیتشان را بررسی کن.',map:'نقشه و مکان‌های کشف‌شده را باز کن.',story:'یک انتخاب انجام بده یا اقدام دلخواهت را بنویس.'})[mode];dock.querySelectorAll('button').forEach(b=>b.classList.toggle('a8-primary',b.dataset.a8===mode));if(mode==='dialogue')dock.querySelector('[data-a8="map"]').textContent='♜ گفتگو';else dock.querySelector('[data-a8="map"]').textContent='⌖ نقشه';dock.dataset.context=mode}
new MutationObserver(sync).observe($('#game-story'),{childList:true,subtree:true});sync();dock.querySelector('[data-a8="map"]').addEventListener('click',e=>{if(dock.dataset.context==='dialogue'){e.stopPropagation();showTab('dialogue')}},true);
const resize=()=>{if(window.innerWidth>850){setup.hidden=false;$('#a8-settings').setAttribute('aria-expanded','true')}else if(!setup.dataset.touched){setup.hidden=true;$('#a8-settings').setAttribute('aria-expanded','false')}};window.addEventListener('resize',resize);resize();
})();