/* Infinite Realms 4.0: explorable world map, quests and adventure log. No Worker changes. */
'use strict';
(()=>{
 const game=document.querySelector('#game');if(!game)return;
 const $=s=>game.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const KEY='infinite-realms-adventure4';let store;try{store=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{store={}};store.campaigns ||= {};
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(store))}catch{status('فضای ذخیره مرورگر پر شده است.')}};
 const cid=()=>$('#game-campaign')?.value||'none';
 const world=()=>store.campaigns[cid()] ||= {locations:[{id:'camp',name:'اردوگاه آغازین',type:'camp',x:50,y:76,known:true,notes:'آغاز ماجراجویی'}],quests:[],events:[],active:'camp'};
 const id=()=>crypto.randomUUID?.()||'x'+Date.now()+Math.random().toString(36).slice(2);
 const tabs=$('.adv-tabs');if(!tabs)return;
 const tab=document.createElement('button');tab.type='button';tab.className='adv-tab';tab.dataset.advTab='world';tab.textContent='🗺 نقشه و مأموریت‌ها';tab.setAttribute('aria-selected','false');tabs.append(tab);
 const panel=document.createElement('section');panel.id='adv-world';panel.className='adv-panel a4-panel';panel.hidden=true;
 panel.innerHTML=`<div class="a4-head"><div><span class="a4-kicker">WORLD EXPLORER</span><h2>🗺 اطلس قلمرو</h2><p>مکان‌ها را کشف کن، مأموریت‌ها را دنبال کن و تاریخچه ماجراجویی‌ات را بساز.</p></div><span id="a4-count" class="a4-chip"></span></div>
 <div class="a4-layout"><div class="a4-map" id="a4-map" role="group" aria-label="نقشه مکان‌های کشف‌شده"><div class="a4-mist"></div><div class="a4-compass">✥<small>شمال</small></div><div id="a4-markers"></div><div class="a4-map-caption">قلمرو ناشناخته · مکان‌ها با پیشرفت تو آشکار می‌شوند</div></div>
 <div class="a4-detail"><h3 id="a4-place-title">اردوگاه آغازین</h3><p id="a4-place-note"></p><div class="a4-actions"><button type="button" id="a4-travel" class="a4-primary">✧ سفر به این مکان</button><button type="button" id="a4-discover">✦ کشف مکان تازه</button></div><form id="a4-place-form" class="a4-form" hidden><label>نام مکان<input name="name" maxlength="55" required placeholder="برج خاموش"></label><label>نوع مکان<select name="type"><option value="castle">قلعه</option><option value="forest">جنگل</option><option value="village">روستا</option><option value="dungeon">سیاهچال</option><option value="ruins">ویرانه</option><option value="camp">اردوگاه</option></select></label><label>یادداشت<textarea name="notes" maxlength="300" rows="2" placeholder="چه چیزی اینجا پیدا کردی؟"></textarea></label><div class="a4-actions"><button class="a4-primary">ثبت روی نقشه</button><button type="button" id="a4-cancel">انصراف</button></div></form><div class="a4-place-list" id="a4-places"></div></div></div>
 <div class="a4-bottom"><section class="a4-quests"><div class="a4-section-head"><h3>📜 دفتر مأموریت‌ها</h3><button type="button" id="a4-add-quest">+ مأموریت</button></div><form id="a4-quest-form" class="a4-form" hidden><label>عنوان مأموریت<input name="title" maxlength="75" required placeholder="راز برج فراموش‌شده"></label><label>شرح مأموریت<textarea name="desc" maxlength="350" rows="2"></textarea></label><button class="a4-primary">ثبت مأموریت</button></form><div id="a4-quest-list"></div></section><section class="a4-chronicle"><div class="a4-section-head"><h3>✒ وقایع سفر</h3><button type="button" id="a4-add-event">+ ثبت واقعه</button></div><form id="a4-event-form" class="a4-form" hidden><label>چه اتفاقی افتاد؟<textarea name="text" maxlength="500" required rows="3" placeholder="دروازه جادویی را پیدا کردیم..."></textarea></label><button class="a4-primary">ثبت در تاریخچه</button></form><div id="a4-events"></div></section></div><p class="a4-disclaimer">مکان‌ها و مأموریت‌ها فعلاً دستی ثبت و در مرورگر همین دستگاه ذخیره می‌شوند؛ DM می‌تواند سفر و مأموریت‌ها را روایت کند، اما خودکار داده‌های نقشه را تغییر نمی‌دهد.</p>`;
 const anchor=$('#adv-inventory')||$('#adv-journal')||$('#adv-battle');anchor.after(panel);
 const status=msg=>{const e=$('#game-feedback');if(e)e.textContent=msg};
 const types={camp:'⛺',castle:'🏰',forest:'🌲',village:'🏘',dungeon:'⚔',ruins:'🏛'};
 const selected=()=>world().locations.find(x=>x.id===world().active)||world().locations[0];
 function render(){const w=world(),p=selected();$('#a4-count').textContent=w.locations.length+' مکان کشف‌شده';$('#a4-place-title').textContent=(types[p.type]||'📍')+' '+p.name;$('#a4-place-note').textContent=p.notes||'هنوز اطلاعاتی از این مکان ثبت نشده.';
 $('#a4-markers').innerHTML=w.locations.map(l=>`<button type="button" class="a4-marker ${l.id===p.id?'selected':''}" style="left:${l.x}%;top:${l.y}%" data-location="${esc(l.id)}" title="${esc(l.name)}" aria-label="${esc(l.name)}"><span>${types[l.type]||'📍'}</span><small>${esc(l.name)}</small></button>`).join('');
 $('#a4-places').innerHTML=w.locations.map(l=>`<button type="button" data-location="${esc(l.id)}" class="${l.id===p.id?'selected':''}">${types[l.type]||'📍'} ${esc(l.name)}</button>`).join('');
 $('#a4-quest-list').innerHTML=w.quests.length?w.quests.map(q=>`<article class="a4-quest ${q.done?'done':''}"><button type="button" data-quest="${esc(q.id)}" aria-label="تغییر وضعیت مأموریت">${q.done?'✓':'○'}</button><div><strong>${esc(q.title)}</strong><p>${esc(q.desc||'بدون شرح')}</p><small>${q.done?'تکمیل‌شده':'در جریان'}</small></div><button type="button" data-delete-quest="${esc(q.id)}" aria-label="حذف مأموریت">×</button></article>`).join(''):'<p class="a4-empty">هنوز مأموریتی ثبت نشده است.</p>';
 $('#a4-events').innerHTML=w.events.length?w.events.slice(0,20).map(e=>`<article class="a4-event"><small>${new Date(e.time).toLocaleDateString('fa-IR')} · ${esc(e.place)}</small><p>${esc(e.text)}</p></article>`).join(''):'<p class="a4-empty">وقایع سفرت اینجا ثبت می‌شوند.</p>';}
 function event(text){const w=world();w.events.unshift({id:id(),time:Date.now(),place:selected().name,text});w.events=w.events.slice(0,100);save();render()}
 function choose(e){const b=e.target.closest('[data-location]');if(!b)return;world().active=b.dataset.location;save();render()}
 $('#a4-markers').addEventListener('click',choose);$('#a4-places').addEventListener('click',choose);
 $('#a4-discover').onclick=()=>{$('#a4-place-form').hidden=false;$('#a4-discover').hidden=true;$('#a4-place-form [name=name]').focus()};
 $('#a4-cancel').onclick=()=>{$('#a4-place-form').hidden=true;$('#a4-discover').hidden=false};
 $('#a4-place-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,n=f.elements.name.value.trim(),notes=f.elements.notes.value.trim();if(!n)return;const w=world();if(w.locations.length>=30)return status('حداکثر ۳۰ مکان برای هر کمپین.');const a=w.locations.length,angle=a*2.39996,r=Math.min(37,14+Math.sqrt(a)*6);const loc={id:id(),name:n,type:f.elements.type.value,notes,x:Math.round(Math.max(8,Math.min(92,50+Math.cos(angle)*r))),y:Math.round(Math.max(12,Math.min(86,50+Math.sin(angle)*r)))};w.locations.push(loc);w.active=loc.id;f.reset();f.hidden=true;$('#a4-discover').hidden=false;event('مکان «'+n+'» کشف شد.');save();render()};
 $('#a4-travel').onclick=()=>{const p=selected(),input=$('#game-input');if(!input)return status('ورودی DM پیدا نشد.');input.value=`من به «${p.name}» سفر می‌کنم. ${p.notes?'آنچه می‌دانم: '+p.notes+'. ':''}صحنه ورود، خطرها و سه انتخاب معنادار را روایت کن؛ هیچ نتیجه تاس را از پیش تعیین نکن.`;event('به سوی «'+p.name+'» حرکت کردیم.');tabs.querySelector('[data-adv-tab="story"]')?.click();input.focus();status('فرمان سفر آماده است؛ برای ارسال، دکمه اقدام را بزن.')};
 $('#a4-add-quest').onclick=()=>{$('#a4-quest-form').hidden=!$('#a4-quest-form').hidden};
 $('#a4-quest-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,title=f.elements.title.value.trim();if(!title)return;world().quests.unshift({id:id(),title,desc:f.elements.desc.value.trim(),done:false});f.reset();f.hidden=true;save();render()};
 $('#a4-quest-list').onclick=e=>{const b=e.target.closest('button');if(!b)return;const w=world(),q=w.quests.find(x=>x.id===(b.dataset.quest||b.dataset.deleteQuest));if(!q)return;if(b.dataset.deleteQuest){if(!confirm('مأموریت حذف شود؟'))return;w.quests=w.quests.filter(x=>x!==q)}else{q.done=!q.done;if(q.done)event('مأموریت «'+q.title+'» تکمیل شد.')}save();render()};
 $('#a4-add-event').onclick=()=>{$('#a4-event-form').hidden=!$('#a4-event-form').hidden};
 $('#a4-event-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,t=f.elements.text.value.trim();if(!t)return;event(t);f.reset();f.hidden=true};
 // Capture phase-2 and phase-3 tabs without modifying their scripts.
 tabs.addEventListener('click',e=>{const b=e.target.closest('[data-adv-tab]');if(!b)return;const on=b===tab;panel.hidden=!on;if(on){['dialogue','battle','journal','inventory'].forEach(n=>{const x=$('#adv-'+n);if(x)x.hidden=true});['#game-story','#game-choices','#game-form'].forEach(s=>{const x=$(s);if(x)x.hidden=true});tabs.querySelectorAll('[data-adv-tab]').forEach(x=>{x.classList.toggle('active',x===tab);x.setAttribute('aria-selected',String(x===tab))});render()}},true);
 $('#game-campaign')?.addEventListener('change',render);render();
})();
