/* Infinite Realms 10 — contextual RPG engine. Works with existing stages, no Worker edit. */
'use strict';(()=>{
const game=document.querySelector('#game');if(!game)return;
const $=s=>game.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='infinite-realms-stage10';let all;try{all=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{all={}};all.campaigns||={};
const campaign=()=>$('#game-campaign')?.value||'none',hero=()=>$('#game-hero')?.value||'none',heroName=()=>$('#game-hero')?.selectedOptions?.[0]?.textContent||'قهرمان';
const rand=n=>{let a=new Uint32Array(1),limit=4294967296-(4294967296%n);do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%n+1};
const uid=()=>crypto.randomUUID?.()||String(Date.now())+Math.random().toString(36).slice(2);
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(all));game.dispatchEvent(new CustomEvent('ir:state-change'))}catch{notice('حافظه مرورگر پر شده؛ خروجی پشتیبان بگیر.')}};
const get=()=>{const c=all.campaigns[campaign()]||={heroes:{},maps:{},activeMap:'overworld',pending:[],journal:[],version:1};c.heroes||={};c.maps||={};c.pending||=[];c.journal||=[];return c};
const heroData=()=>{const c=get(),id=hero();if(!c.heroes[id]){let old={};try{old=JSON.parse(localStorage.getItem('infinite-realms-adventure3')||'{}').campaigns?.[campaign()]||{}}catch{};const migrate=Object.keys(c.heroes).length===0;c.heroes[id]={items:(migrate?old.items||[]:[]).map(i=>({...i,id:i.id||uid(),type:'item'})),gold:migrate?old.gold||0:0,spells:[],learned:[],xp:0,initialized:true}}return c.heroes[id]};
const className=()=>{let c='';try{c=JSON.parse(localStorage.getItem('infinite-realms-db')||'{}').characters?.find(x=>x.id===hero())?.klass||''}catch{};return c||heroName().split(' · ').at(-1)||'Fighter'};
const heroLevel=()=>{const text=heroName();let h=window.db?.characters?.find(x=>x.id===hero());return Math.max(1,Math.min(20,Number(h?.level||text.match(/سطح\s*(\d+)/)?.[1]||1)))};
const SPELLS=[
{name:'جرقه جادویی',klass:['Wizard','Sorcerer','Warlock'],level:1,slot:0,desc:'یک حمله جادویی ساده؛ تاس آسیب را با DM هماهنگ کن.'},
{name:'سپر جادویی',klass:['Wizard','Sorcerer'],level:1,slot:1,desc:'واکنش دفاعی؛ یک جایگاه جادوی سطح ۱ مصرف می‌شود.'},
{name:'درمان زخم',klass:['Cleric','Druid','Bard','Paladin','Ranger'],level:1,slot:1,desc:'درمان بر اساس تاس و اصلاح‌کننده مربوط به کلاس.'},
{name:'پرتاب آتش',klass:['Wizard','Sorcerer'],level:3,slot:2,desc:'جادوی سطح ۲؛ آسیب و نجات را DM تعیین می‌کند.'},
{name:'ردیابی شکار',klass:['Ranger','Druid'],level:1,slot:1,desc:'ردیابی هدف در محیط.'},
{name:'الهام حماسی',klass:['Bard'],level:1,slot:0,desc:'الهام برای هم‌گروهی؛ محدودیت کلاس را با DM بررسی کن.'},
{name:'ضربه مقدس',klass:['Paladin'],level:2,slot:1,desc:'مصرف جایگاه جادو پس از اصابت؛ آسیب اضافه با DM.'},
{name:'خشم جنگی',klass:['Barbarian'],level:1,slot:0,desc:'توانایی کلاس؛ تعداد دفعات مجاز را DM بررسی کند.'},
{name:'حمله غافلگیرانه',klass:['Rogue'],level:1,slot:0,desc:'در صورت احراز شرایط، آسیب اضافی.'},
{name:'نفس دوم',klass:['Fighter'],level:1,slot:0,desc:'بازیابی جان طبق سطح کلاس؛ استفاده دوباره بعد از استراحت مناسب.'},
{name:'کی',klass:['Monk'],level:2,slot:0,desc:'استفاده از امتیازهای کی طبق سطح و قوانین کمپین.'}
];
const mapTypes=[['overworld','🌍 قلمرو اصلی','کوهستان','جنگل','روستا','دژ','دریاچه','ویرانه','معبد','دره','اردوگاه'],['underworld','🕯 اعماق تاریک','دروازه','تالار','گذرگاه','مقبره','چاه','خزانه','سیاهچال','پناهگاه','محراب'],['wilds','🌲 جنگل مه‌آلود','اردوگاه','درخت کهن','رودخانه','مرداب','برج','غار','آبشار','معبد','دشت']];
const seed=str=>{let h=2166136261;for(const c of str){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function map(id){const c=get();if(c.maps[id])return c.maps[id];const types=mapTypes.find(x=>x[0]===id)||mapTypes[0];let n=seed(campaign()+id),rnd=()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296};const places=types.slice(2).map((name,i)=>({id:id+'-'+i,name,x:12+(i%3)*36+(rnd()-.5)*12,y:16+Math.floor(i/3)*31+(rnd()-.5)*12,known:i===0,visited:i===0,note:'',type:i===0?'camp':i%3===0?'castle':i%3===1?'forest':'ruins'}));return c.maps[id]={places,active:places[0].id};}
const currentPlace=()=>{const c=get(),m=map(c.activeMap);return m.places.find(x=>x.id===m.active)||m.places[0]};
let viewedMap=null;const viewing=()=>viewedMap||get().activeMap;
const addLog=text=>{get().journal.unshift({id:uid(),text,time:Date.now(),place:currentPlace().name});get().journal=get().journal.slice(0,100);save()};
const stage=document.createElement('div');stage.className='a10-root';stage.innerHTML=`<button class="a10-fab" id="a10-fab" type="button" aria-label="بازکردن منوی بازی" aria-expanded="false">☰<small>بازی</small></button><div id="a10-backdrop" class="a10-backdrop" hidden></div><section id="a10-sheet" class="a10-sheet" role="dialog" aria-modal="true" aria-labelledby="a10-title" hidden><header><h2 id="a10-title">⚜ منوی ماجراجویی</h2><button id="a10-close" type="button">✕</button></header><div id="a10-content"></div></section><div class="a10-status" id="a10-status" role="status" aria-live="polite"></div><div class="a10-offer" id="a10-offer" hidden></div>`;game.append(stage);
const content=$('#a10-content'),sheet=$('#a10-sheet'),fab=$('#a10-fab');let lastFocus=null;
function notice(t){const n=$('#a10-status');n.textContent=t;n.classList.add('show');clearTimeout(notice.t);notice.t=setTimeout(()=>n.classList.remove('show'),4500)}
function close(){sheet.hidden=true;$('#a10-backdrop').hidden=true;fab.setAttribute('aria-expanded','false');lastFocus?.focus?.()}
function open(title,html){lastFocus=document.activeElement;$('#a10-title').textContent=title;content.innerHTML=html;sheet.hidden=false;$('#a10-backdrop').hidden=false;fab.setAttribute('aria-expanded','true');$('#a10-close').focus()}
function send(text){close();let input=$('#game-input');if(!input)return;input.value=text;$('#game-form')?.requestSubmit()}
function menu(){open('⚜ منوی ماجراجویی',`<div class="a10-menu"><button data-open="context">⚡ اقدام مناسب موقعیت</button><button data-open="inventory">🎒 کوله‌پشتی <small>${heroData().items.reduce((s,i)=>s+i.count,0)} وسیله</small></button><button data-open="abilities">✨ مهارت‌ها و جادو</button><button data-open="battle">⚔ نبرد و دفاع</button><button data-open="map">🗺 اطلس قلمروها</button><button data-open="hero">♥ قهرمان</button><button data-open="quests">📜 مأموریت و وقایع</button><button data-open="pending">✓ رویدادهای در انتظار تأیید</button><button data-open="dice">⚄ تاس</button><button data-open="legacy">⚙ ابزارهای پیشرفته</button></div>`)}
function contextMode(){const txt=[...game.querySelectorAll('#game-story .game-narrator p')].at(-1)?.textContent||'';return /نبرد|حمله|دشمن|اژدها|مبارزه/i.test(txt)?'battle':/گفتگو|بازرگان|نگهبان|صحبت/i.test(txt)?'dialogue':/سفر|جاده|روستا|شهر|جنگل|نقشه/i.test(txt)?'travel':'explore'}
function context(){const mode=contextMode(),actions={battle:[['⚔ حمله','battle'],['⛨ دفاع','defend'],['✨ جادو','abilities'],['🎒 آیتم','inventory']],dialogue:[['♜ گفتگو','talk'],['🧠 تشخیص نیت','insight'],['🎒 هدیه دادن','inventory'],['🗺 نقشه','map']],travel:[['🗺 نقشه','map'],['👁 بررسی محیط','look'],['🎒 تجهیزات','inventory'],['✨ جادو','abilities']],explore:[['👁 بررسی محیط','look'],['🗺 نقشه','map'],['🎒 کوله‌پشتی','inventory'],['⚄ تاس','dice']]};open('⚡ اقدام متناسب با موقعیت',`<p class="a10-note">ابزارهای مناسب این صحنه؛ همچنان می‌توانی هر اقدام دلخواهی بنویسی.</p><div class="a10-menu">${actions[mode].map(([t,id])=>`<button data-open="${id}">${t}</button>`).join('')}</div>`)}
function inventory(){const h=heroData();open('🎒 کوله‌پشتی '+heroName().split(' · ')[0],`<div class="a10-purse">🪙 طلا: <strong>${h.gold}</strong></div><div class="a10-list">${h.items.map(i=>`<article><div><strong>${esc(i.name)}</strong><small>تعداد: ${i.count} · ${esc(i.type||'وسیله')}</small></div><div class="a10-row"><button data-use="${esc(i.id)}">${/معجون|potion|خوراک|غذا/i.test(i.name)?'مصرف':'استفاده'}</button><button data-equip="${esc(i.id)}">${i.equipped?'✓ مجهز':'تجهیز'}</button></div></article>`).join('')||'<p>کوله‌پشتی خالی است.</p>'}</div><form id="a10-add-item" class="a10-form"><label>نام آیتم<input name="name" required maxlength="70" placeholder="مثلاً معجون درمان"></label><label>تعداد<input name="count" type="number" min="1" max="99" value="1"></label><button type="submit">+ افزودن</button></form><p class="a10-note">دریافت آیتم از AI ابتدا برای تأیید نمایش داده می‌شود. مصرف و تجهیز در وضعیت بازی ثبت می‌شوند.</p>`)}
function mirrorItems(){let old;try{old=JSON.parse(localStorage.getItem('infinite-realms-adventure3')||'{}')}catch{old={}};old.campaigns||={};let c=old.campaigns[campaign()]||={};c.items=heroData().items.map(i=>({id:i.id,name:i.name,count:i.count}));c.gold=heroData().gold;localStorage.setItem('infinite-realms-adventure3',JSON.stringify(old))}
function abilities(){const h=heroData(),klass=className(),level=heroLevel();const available=SPELLS.filter(s=>s.klass.some(c=>klass.toLowerCase().includes(c.toLowerCase()))&&s.level<=level);open('✨ توانایی‌های '+esc(klass),`<p class="a10-note">کلاس: ${esc(klass)} · سطح ${level} · توانایی‌های پیشنهادی کلاس؛ ویژگی‌های خاص با DM بررسی می‌شوند.</p><div class="a10-list">${available.map(s=>`<article><div><strong>${esc(s.name)}</strong><small>${esc(s.desc)}</small></div><button data-spell="${esc(s.name)}" data-slot="${s.slot}">${s.slot?'استفاده · سطح '+s.slot:'استفاده'}</button></article>`).join('')||'<p>توانایی پیش‌فرض این کلاس در این سطح تعریف نشده است. می‌توانی مهارت اکتسابی ثبت کنی.</p>'}${h.learned.map(s=>`<article><div><strong>✦ ${esc(s)}</strong><small>مهارت اکتسابی این قهرمان</small></div><button data-spell="${esc(s)}" data-slot="0">استفاده</button></article>`).join('')}</div><form id="a10-learn" class="a10-form"><label>مهارت جدیدی که واقعاً کسب کردی<input name="name" maxlength="65" required placeholder="نام توانایی"></label><button>ثبت مهارت</button></form><button data-open="legacy-rules">⚙ جایگاه‌های جادو و قوانین کامل</button>`)}
function ruleState(){let all7;try{all7=JSON.parse(localStorage.getItem('infinite-realms-adventure7')||'{}')}catch{all7={}};return {all7,s:all7[campaign()]||null}}
function useSpell(name,slot){const known=[...SPELLS.filter(s=>s.klass.some(c=>className().toLowerCase().includes(c.toLowerCase()))&&s.level<=heroLevel()).map(s=>s.name),...heroData().learned];if(!known.includes(name))return notice('این توانایی برای قهرمان فعلی باز نیست.');if(slot){const {all7,s}=ruleState();if(!s)return notice('ابتدا جایگاه‌های جادو را در برگه قوانین تنظیم کن.');if((s.slots?.[slot-1]||0)<1)return notice('جایگاه جادوی کافی نداری.');}if(slot)queueCost({type:'spend_slot',slot,name});send('قصد استفاده از توانایی «'+name+'» را دارم. '+(slot?'برای آن یک جایگاه جادوی سطح '+slot+' لازم است. ':'')+'اگر نیاز به تاس یا شرطی است، اعلام کن و منتظر نتیجه من بمان. منابع فقط پس از تأیید من مصرف می‌شوند.')}
function battle(){const {s}=ruleState();open('⚔ نبرد و دفاع',`<p class="a10-note">${s?'♥ '+s.hp+'/'+s.max+' · ⛨ AC '+s.ac:'ابتدا برگه قهرمان را تکمیل کن.'}</p><div class="a10-menu"><button data-open="attack">⚔ حمله و هدف‌گیری</button><button data-open="defend">⛨ دفاع</button><button data-open="abilities">✨ جادو و توانایی</button><button data-open="inventory">🎒 معجون و تجهیزات</button><button data-open="dice">⚄ تاس سریع</button><button data-open="legacy-battle">♟ میدان نبرد پیشرفته</button></div>`)}
function dice(){open('⚄ تاس سرنوشت',`<div class="a10-menu">${[4,6,8,10,12,20,100].map(n=>`<button data-die="${n}">D${n}</button>`).join('')}</div><div id="a10-roll" class="a10-roll">یک تاس انتخاب کن.</div><button id="a10-send-roll" hidden>اعلام نتیجه به DM</button>`)}
function svgMap(m,id){const p=m.places;let paths=p.slice(1).map((x,i)=>`<path d="M ${p[i].x*7} ${p[i].y*4} Q ${350+(i%2?80:-80)} ${190+(i%3)*30} ${x.x*7} ${x.y*4}" fill="none" stroke="#bb985d" stroke-opacity=".34" stroke-width="2" stroke-dasharray="5 6"/>`).join('');let terrain=Array.from({length:28},(_,i)=>{let n=seed(campaign()+id+i),x=n%680+10,y=(n>>>10)%375+12;return `<path d="M${x} ${y+13}l10 -22 10 22z" fill="${id==='wilds'?'#37624f':'#4a5a54'}" opacity=".35"/>`}).join('');let points=p.map(x=>`<g class="a10-map-point ${x.known?'':'locked'} ${m.active===x.id?'active':''} ${m.selected===x.id?'selected':''}" data-place="${esc(x.id)}" tabindex="0" role="button" aria-label="${esc(x.known?x.name:'مکان ناشناخته')}"><circle cx="${x.x*7}" cy="${x.y*4}" r="15"/><text x="${x.x*7}" y="${x.y*4+5}" text-anchor="middle" font-size="16">${x.known?(x.type==='camp'?'⛺':x.type==='forest'?'🌲':'🏰'):'?'}</text><text x="${x.x*7}" y="${x.y*4+29}" text-anchor="middle" font-size="12">${esc(x.known?x.name:'ناشناخته')}</text></g>`).join('');return `<svg class="a10-map-svg" viewBox="0 0 700 420" role="img" aria-label="نقشه کامل قلمرو"><defs><linearGradient id="a10-land" x2="1" y2="1"><stop stop-color="#233e37"/><stop offset="1" stop-color="#182330"/></linearGradient><pattern id="a10-grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="#d5ba8050" stroke-width=".6"/></pattern></defs><rect width="700" height="420" fill="url(#a10-land)"/><path d="M0 90Q100 30 190 120T380 100T700 120V0H0Z" fill="#34495a" opacity=".6"/><path d="M0 320Q160 230 270 330T700 310V420H0Z" fill="#304936" opacity=".6"/>${terrain}<rect width="700" height="420" fill="url(#a10-grid)"/>${paths}${points}<text x="652" y="40" fill="#e7cb94" font-size="30">✥</text></svg>`}
function maps(){const c=get(),m=map(viewing()),active=m.places.find(x=>x.id===(m.selected||m.active))||m.places[0];open('🗺 اطلس زنده قلمروها',`<div class="a10-map-tabs">${mapTypes.map(x=>`<button data-map="${x[0]}" ${viewing()===x[0]?'class="active"':''}>${x[1]}</button>`).join('')}</div>${svgMap(m,viewing())}<div class="a10-place"><h3>${esc(active.known?active.name:'مکان ناشناخته')}</h3><p>${esc(active.note||'برای کشف مسیر، مکان‌های مجاور را بررسی کن.')}</p><div class="a10-row"><button data-travel="${esc(active.id)}" ${!active.known?'disabled':''}>➤ سفر به مکان</button><button data-discover="${esc(active.id)}" ${active.known?'disabled':''}>✦ کشف این مکان</button></div></div><p class="a10-note">هر کمپین سه نقشه کامل و مستقل دارد؛ مکان‌های ناشناخته با پیشرفت داستان آشکار می‌شوند. سفر واقعی پس از تأیید راوی ثبت می‌شود.</p>`)}
function quests(){const c=get();let w={};try{w=JSON.parse(localStorage.getItem('infinite-realms-adventure4')||'{}').campaigns?.[campaign()]||{}}catch{};open('📜 مأموریت‌ها و وقایع',`<h3>مأموریت‌ها</h3><div class="a10-list">${(w.quests||[]).map(q=>`<article><strong>${esc(q.title)}</strong><small>${q.done?'✓ انجام شده':'○ در جریان'}</small></article>`).join('')||'<p>هنوز مأموریتی ثبت نشده است.</p>'}</div><h3>وقایع زنده</h3><div class="a10-list">${c.journal.slice(0,25).map(e=>`<article><small>${new Date(e.time).toLocaleString('fa-IR')} · ${esc(e.place)}</small><div>${esc(e.text)}</div></article>`).join('')||'<p>هنوز رویدادی ثبت نشده است.</p>'}</div><button data-open="legacy-map">ویرایش نقشه و مأموریت‌های قبلی</button>`)}
function legacy(which){close();if(which==='hero'){$('#a9-hero')?.click();return}if(which==='settings'){$('#a9-settings')?.click();return}const tab={battle:'battle',map:'world',rules:'rules'}[which]||'story';$('#a9-fab')?.click();const a9=[...game.querySelectorAll('.a9-menu button')].find(b=>b.textContent.includes(which==='battle'?'مبارزه':which==='map'?'نقشه':'مهارت'));if(a9)a9.click();else{$('.adv-tabs [data-adv-tab="'+tab+'"]')?.click();notice('ابزار پیشرفته از منوی قبلی در دسترس است.')}}
function legacyMenu(){open('⚙ ابزارهای پیشرفته',`<div class="a10-menu"><button data-open="legacy-battle">مبارزه پیشرفته</button><button data-open="legacy-map">ویرایش نقشه و مأموریت</button><button data-open="legacy-rules">قوانین کامل قهرمان</button><button data-open="legacy-hero">برگه قهرمان قبلی</button><button data-open="legacy-settings">کمپین و ذخیره ابری</button><button data-open="backup">↓ خروجی پشتیبان جدید</button></div>`)}
function backup(){const data={version:14,exported:new Date().toISOString(),campaignId:campaign(),state:get(),rules:(()=>{try{return JSON.parse(localStorage.getItem('infinite-realms-adventure7')||'{}')[campaign()]}catch{return null}})()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='infinite-realms-stage10-'+campaign()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);notice('پشتیبان دریافت شد')}
function openBy(id){if(id==='context')return context();if(id==='inventory')return inventory();if(id==='abilities')return abilities();if(id==='battle')return battle();if(id==='map')return maps();if(id==='quests')return quests();if(id==='pending'){close();return offers([],true)}if(id==='dice')return dice();if(id==='hero')return legacy('hero');if(id==='legacy')return legacyMenu();if(id==='backup')return backup();if(id.startsWith('legacy-'))return legacy(id.slice(7));if(id==='look')return send('با دقت محیط اطرافم را بررسی می‌کنم؛ سرنخ‌ها و خطرها را شرح بده.');if(id==='talk')return send('با شخصیت حاضر گفتگو می‌کنم.');if(id==='insight')return send('سعی می‌کنم نیت او را تشخیص دهم؛ آزمون مناسب و DC را بگو.');if(id==='defend'){addLog('⛨ قهرمان حالت دفاعی گرفت.');return send('اقدام دفاعی انجام می‌دهم؛ اثر آن را طبق نوبت و شرایط نبرد محاسبه کن.')}if(id==='attack')return send('می‌خواهم حمله کنم. هدف، نوع حمله و تاس لازم را مشخص کن و منتظر تاس من بمان.')}
content.addEventListener('click',e=>{const point=e.target.closest('[data-place]');if(point){const m=map(viewing());m.selected=point.dataset.place;maps();return}const b=e.target.closest('button');if(!b)return;if(b.dataset.open)return openBy(b.dataset.open);if(b.dataset.die){const n=+b.dataset.die,v=rand(n);$('#a10-roll').textContent='⚄ D'+n+' = '+v;const x=$('#a10-send-roll');x.hidden=false;x.onclick=()=>send('نتیجه تاس واقعی من D'+n+' برابر '+v+' شد. با توجه به قوانین و شرایط، نتیجه را اعمال کن.');return}if(b.dataset.use){const h=heroData(),i=h.items.find(x=>x.id===b.dataset.use);if(!i)return;if(i.count<1)return notice('این آیتم تمام شده است');queueCost({type:'lose_item',name:i.name,amount:1});return send('قصد استفاده از آیتم «'+i.name+'» را دارم. اگر استفاده مجاز است نتیجه را شرح بده؛ مصرف آیتم فقط بعد از تأیید من ثبت می‌شود.')}if(b.dataset.equip){const i=heroData().items.find(x=>x.id===b.dataset.equip);if(!i)return;i.equipped=!i.equipped;addLog('🎒 '+i.name+(i.equipped?' تجهیز شد':' کنار گذاشته شد'));return inventory()}if(b.dataset.spell)return useSpell(b.dataset.spell,+b.dataset.slot);if(b.dataset.map){viewedMap=b.dataset.map;return maps()}if(b.dataset.place){const m=map(viewing());m.selected=b.dataset.place;return maps()}if(b.dataset.discover){const m=map(viewing()),p=m.places.find(x=>x.id===b.dataset.discover);if(!p)return;p.known=true;addLog('🗺 مکان تازه کشف شد: '+p.name);return maps()}if(b.dataset.travel){const m=map(viewing()),p=m.places.find(x=>x.id===b.dataset.travel);if(!p||!p.known)return;return send('قصد سفر به «'+p.name+'» در '+viewing()+' را دارم. مسیر، خطر و زمان سفر را شرح بده و ورود را بعد از اقدام من تأیید کن.') }});
content.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-place]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}))}});
content.addEventListener('submit',e=>{if(e.target.id==='a10-add-item'){e.preventDefault();const f=e.target,n=f.elements.name.value.trim(),count=+f.elements.count.value;if(!n||!Number.isInteger(count)||count<1||count>99)return;const h=heroData(),old=h.items.find(x=>x.name===n);if(old)old.count+=count;else h.items.push({id:uid(),name:n,count,type:'item'});mirrorItems();addLog('🎒 '+count+' عدد '+n+' به کوله‌پشتی افزوده شد');inventory()}if(e.target.id==='a10-learn'){e.preventDefault();const n=e.target.elements.name.value.trim();if(!n)return;const h=heroData();if(!h.learned.includes(n))h.learned.push(n);addLog('✨ مهارت تازه: '+n);abilities()}});
$('#a10-fab').onclick=()=>sheet.hidden?menu():close();$('#a10-close').onclick=close;$('#a10-backdrop').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!sheet.hidden)close()});
// A resource is reserved locally, not consumed before the DM replies and player approves.
let queuedCost=null;function queueCost(cost){queuedCost={...cost,campaignId:campaign(),heroId:hero()};notice('منبع هنوز مصرف نشده؛ پس از پاسخ راوی تأیید کن.')}
$('#game-form')?.addEventListener('submit',()=>{if(queuedCost&&queuedCost.campaignId!==campaign())queuedCost=null});
// AI proposals are untrusted suggestions: validate, show to the player and apply only on approval.
const allowed=new Set(['gain_item','lose_item','gain_gold','lose_gold','learn_ability','discover_place','travel','damage','heal','quest_note']);
function validate(event){if(!event||!allowed.has(event.type))return null;const e={type:event.type,name:String(event.name||'').slice(0,65),amount:Math.min(1000,Math.max(1,Math.floor(+event.amount||1))),map:mapTypes.some(m=>m[0]===event.map)?event.map:'overworld',place:String(event.place||'').slice(0,65)};if(['gain_item','lose_item','learn_ability','quest_note'].includes(e.type)&&!e.name)return null;if(['travel','discover_place'].includes(e.type)&&!e.place)return null;return e}
const label=e=>({gain_item:'🎒 دریافت '+e.amount+' × '+e.name,lose_item:'🎒 مصرف '+e.amount+' × '+e.name,gain_gold:'🪙 دریافت '+e.amount+' طلا',lose_gold:'🪙 پرداخت '+e.amount+' طلا',learn_ability:'✨ یادگیری '+e.name,discover_place:'🗺 کشف '+e.place,travel:'➤ ورود به '+e.place,damage:'⚔ دریافت '+e.amount+' آسیب',heal:'✚ بازیابی '+e.amount+' جان',quest_note:'📜 '+e.name,spend_slot:'✨ مصرف جایگاه جادوی سطح '+e.slot})[e.type];
function apply(e){const h=heroData(),c=get();if(e.type==='gain_item'){const i=h.items.find(x=>x.name===e.name);if(i)i.count+=e.amount;else h.items.push({id:uid(),name:e.name,count:e.amount,type:'item'});mirrorItems()}else if(e.type==='lose_item'){const i=h.items.find(x=>x.name===e.name);if(!i||i.count<e.amount){notice('آیتم کافی در کوله‌پشتی نیست');return false}i.count-=e.amount;if(!i.count)h.items=h.items.filter(x=>x!==i);mirrorItems()}else if(e.type==='gain_gold'||e.type==='lose_gold'){if(e.type==='lose_gold'&&h.gold<e.amount){notice('طلای کافی نداری');return false}h.gold=Math.max(0,h.gold+(e.type==='gain_gold'?e.amount:-e.amount));mirrorItems()}else if(e.type==='learn_ability'){if(!h.learned.includes(e.name))h.learned.push(e.name)}else if(e.type==='discover_place'){const m=map(e.map),p=m.places.find(x=>x.name===e.place)||m.places.find(x=>!x.known);if(p){p.known=true;if(e.place)p.name=e.place.slice(0,45);}}else if(e.type==='travel'){const m=map(e.map),p=m.places.find(x=>x.name===e.place||x.id===e.place);if(!p||!p.known){notice('ابتدا این مکان باید کشف شود');return false}m.active=p.id;p.visited=true;c.activeMap=e.map}else if(e.type==='spend_slot'){const {all7,s}=ruleState();if(!s||(+s.slots?.[e.slot-1]||0)<1){notice('جایگاه جادوی کافی نداری');return false}s.slots[e.slot-1]--;localStorage.setItem('infinite-realms-adventure7',JSON.stringify(all7))}else if(e.type==='damage'||e.type==='heal'){const {all7,s}=ruleState();if(!s){notice('ابتدا برگه قهرمان را تنظیم کن');return false}if(e.type==='damage'){const absorb=Math.min(s.temp||0,e.amount);s.temp=(s.temp||0)-absorb;s.hp=Math.max(0,s.hp-(e.amount-absorb))}else s.hp=Math.min(s.max,s.hp+e.amount);localStorage.setItem('infinite-realms-adventure7',JSON.stringify(all7))}addLog(label(e))}
function offers(list,restored=false){
 const c=get();if(!Array.isArray(c.pending))c.pending=[];
 if(!restored){const arr=(Array.isArray(list)?list:[]).map(validate).filter(Boolean).slice(0,5);if(queuedCost&&queuedCost.campaignId===campaign()&&queuedCost.heroId===hero()){arr.unshift(queuedCost);queuedCost=null}
 for(const e of arr)c.pending.push({...e,heroId:hero(),id:uid()});c.pending=c.pending.slice(-30);save()}
 const pending=c.pending.filter(e=>e.heroId===hero());const wrap=$('#a10-offer');if(!pending.length){wrap.hidden=true;return}
 wrap.hidden=false;wrap.innerHTML='<strong>✦ رویدادهای در انتظار تأیید</strong>'+pending.map(e=>`<div class="a10-offer-row"><span>${esc(label(e))}</span><button data-approve="${esc(e.id)}">تأیید</button><button data-reject="${esc(e.id)}">رد</button></div>`).join('')+'<button id="a10-dismiss">بعداً بررسی می‌کنم</button>';
 wrap.onclick=ev=>{const b=ev.target.closest('button');if(!b)return;if(b.id==='a10-dismiss'){wrap.hidden=true;return}const id=b.dataset.approve||b.dataset.reject,e=c.pending.find(x=>x.id===id&&x.heroId===hero());if(!e)return notice('رویداد معتبر پیدا نشد');if(b.dataset.approve){if(apply(e)===false)return}c.pending=c.pending.filter(x=>x.id!==id);save();offers([],true)};
}
game.addEventListener('ir:ai-error',()=>{queuedCost=null;notice('درخواست انجام نشد؛ هیچ منبعی مصرف نشد')});game.addEventListener('ir:ai-turn',e=>{if(e.detail?.campaignId!==campaign()||e.detail?.heroId!==hero())return;offers(e.detail.events)});
// Update compact HUD without changing the original game engine.
const hud=document.createElement('div');hud.className='a10-hud';game.querySelector('.a9-head')?.append(hud);function hudUpdate(){const {s}=ruleState();const h=heroData();hud.textContent=(s?'♥ '+s.hp+'/'+s.max+'  ·  ':'')+'🎒 '+h.items.reduce((n,i)=>n+i.count,0)+'  ·  🪙 '+h.gold}window.addEventListener('ir:cloud-restored',()=>{try{all=JSON.parse(localStorage.getItem(KEY)||'{}');all.campaigns||={}}catch{}hudUpdate();offers([],true)});game.addEventListener('ir:state-change',hudUpdate);$('#game-hero')?.addEventListener('change',hudUpdate);$('#game-campaign')?.addEventListener('change',hudUpdate);hudUpdate();if(get().pending?.length)offers([],true);$('#game-campaign')?.addEventListener('change',()=>offers([],true));$('#game-hero')?.addEventListener('change',()=>offers([],true))
// Small context indicator, no permanent bottom bar.
const badge=document.createElement('span');badge.className='a10-context-badge';game.querySelector('.a9-head')?.append(badge);const updateContext=()=>{badge.textContent=({battle:'⚔ نبرد',dialogue:'♜ گفتگو',travel:'🗺 سفر',explore:'✦ اکتشاف'})[contextMode()]};new MutationObserver(updateContext).observe($('#game-story'),{childList:true,subtree:true});updateContext();
})();
