/* Infinite Realms 5.0 — NPC codex, relationships and immersive encounters. */
'use strict';
(()=>{
 const game=document.getElementById('game');if(!game)return;
 const $=s=>game.querySelector(s),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const KEY='infinite-realms-adventure5';let db5={};try{db5=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};db5.campaigns||={};
 const cid=()=>$('#game-campaign')?.value||'none',data=()=>db5.campaigns[cid()]||={npcs:[],active:null};
 const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(db5))}catch{feedback('فضای ذخیره مرورگر کافی نیست.')}};
 const feedback=t=>{if($('#game-feedback'))$('#game-feedback').textContent=t};
 const id=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
 const tabs=$('.adv-tabs');if(!tabs)return;
 const tab=document.createElement('button');tab.type='button';tab.className='adv-tab';tab.dataset.advTab='npcs';tab.textContent='♜ شخصیت‌های جهان';tab.setAttribute('aria-selected','false');tabs.append(tab);
 const panel=document.createElement('section');panel.id='adv-npcs';panel.className='adv-panel a5-panel';panel.hidden=true;
 panel.innerHTML=`<header class="a5-head"><div><span class="a5-kicker">THE LIVING WORLD</span><h2>♜ شخصیت‌های جهان</h2><p>دوستان، دشمنان و غریبه‌ها را به یاد بسپار؛ روابط تو در هر کمپین جداگانه ذخیره می‌شود.</p></div><button type="button" id="a5-add">+ شخصیت جدید</button></header>
 <div class="a5-grid"><div class="a5-roster"><div class="a5-roster-title">✧ شخصیت‌های ملاقات‌شده <span id="a5-count"></span></div><div id="a5-list"></div></div><div class="a5-profile" id="a5-profile"><div class="a5-empty">هنوز کسی را ملاقات نکرده‌ای. شخصیت جدید ثبت کن یا از راوی بخواه کسی را معرفی کند.</div></div></div>
 <dialog id="a5-dialog"><form id="a5-form" method="dialog"><div class="a5-modal-head"><h3>ثبت شخصیت داستان</h3><button type="button" id="a5-close" aria-label="بستن">✕</button></div><label>نام شخصیت<input name="name" required maxlength="55" placeholder="مثلاً اِلارا، نگهبان برج"></label><label>نقش<select name="role"><option>همراه</option><option>غریبه</option><option>تاجر</option><option>راهنما</option><option>دشمن</option><option>شخصیت مرموز</option></select></label><label>مکان ملاقات<input name="location" maxlength="65" placeholder="اردوگاه آغازین"></label><label>توصیف و رازهای کشف‌شده<textarea name="notes" maxlength="900" rows="4" placeholder="چه چیزی درباره‌اش می‌دانی؟"></textarea></label><button class="a5-primary" type="submit">ثبت شخصیت</button></form></dialog>
 <p class="a5-hint">روابط و یادداشت‌ها فعلاً روی همین مرورگر ذخیره می‌شوند؛ DM برای حفظ پیوستگی، خلاصه شخصیت انتخاب‌شده را همراه فرمان گفتگو دریافت می‌کند. تغییر رابطه خودکار نیست.</p>`;
 ($('#adv-world')||$('#adv-inventory')||$('#adv-journal')).after(panel);
 const $p=s=>panel.querySelector(s),mood=n=>n>=65?'متحد':n>=25?'دوست':n>-25?'خنثی':n>-65?'بی‌اعتماد':'دشمن';
 function render(){const d=data();$p('#a5-count').textContent=d.npcs.length+' نفر';$p('#a5-list').innerHTML=d.npcs.length?d.npcs.map(n=>`<button type="button" class="a5-person ${d.active===n.id?'active':''}" data-npc="${safe(n.id)}"><span class="a5-portrait">${n.role==='دشمن'?'⚔':n.role==='تاجر'?'⚖':'♜'}</span><span><strong>${safe(n.name)}</strong><small>${safe(n.role)} · ${mood(n.affinity)}</small></span><span class="a5-dot"></span></button>`).join(''):'<p class="a5-hint">شخصیتی ثبت نشده است.</p>';
 const n=d.npcs.find(n=>n.id===d.active)||d.npcs[0];if(!n){$p('#a5-profile').innerHTML='<div class="a5-empty">شخصیتی را انتخاب کن یا یک شخصیت تازه بساز.</div>';return}d.active=n.id;
 $p('#a5-profile').innerHTML=`<div class="a5-hero"><div class="a5-avatar">♜</div><div><small>PERSON OF INTEREST</small><h3>${safe(n.name)}</h3><p>${safe(n.role)} · ${safe(n.location||'مکان نامشخص')}</p></div></div><div class="a5-affinity"><div><strong>رابطه: ${mood(n.affinity)}</strong><span>${n.affinity>0?'+':''}${n.affinity}</span></div><div class="a5-meter"><i style="width:${Math.max(0,Math.min(100,(n.affinity+100)/2))}%"></i></div><div class="a5-affinity-buttons"><button type="button" data-affinity="-10">− کاهش اعتماد</button><button type="button" data-affinity="10">+ افزایش اعتماد</button></div></div><label class="a5-notes-label">✒ یادداشت و سرنخ‌ها<textarea id="a5-notes" maxlength="900" rows="4" placeholder="اطلاعات تازه را ثبت کن...">${safe(n.notes||'')}</textarea></label><div class="a5-actions"><button type="button" class="a5-primary" data-speak="talk">◈ شروع گفتگو</button><button type="button" data-speak="persuade">✧ متقاعدسازی</button><button type="button" data-speak="insight">◉ تشخیص نیت</button><button type="button" data-speak="quest">📜 درخواست مأموریت</button></div><button type="button" class="a5-delete" id="a5-delete">حذف این شخصیت</button>`;
 $p('#a5-notes').addEventListener('change',e=>{n.notes=e.target.value;persist()});$p('#a5-delete').onclick=()=>{if(!confirm('این شخصیت از دفتر حذف شود؟'))return;d.npcs=d.npcs.filter(x=>x!==n);d.active=d.npcs[0]?.id||null;persist();render()};persist()}
 $p('#a5-add').onclick=()=>{$p('#a5-dialog').showModal()};$p('#a5-close').onclick=()=>$p('#a5-dialog').close();
 $p('#a5-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,n=f.elements.name.value.trim();if(!n)return;if(data().npcs.length>=60)return feedback('حداکثر ۶۰ شخصیت برای هر کمپین.');const npc={id:id(),name:n,role:f.elements.role.value,location:f.elements.location.value.trim(),notes:f.elements.notes.value.trim(),affinity:0};data().npcs.unshift(npc);data().active=npc.id;persist();f.reset();$p('#a5-dialog').close();render()};
 $p('#a5-list').onclick=e=>{const b=e.target.closest('[data-npc]');if(!b)return;data().active=b.dataset.npc;persist();render()};
 $p('#a5-profile').onclick=e=>{const b=e.target.closest('button');if(!b)return;const d=data(),n=d.npcs.find(x=>x.id===d.active);if(!n)return;if(b.dataset.affinity){n.affinity=Math.max(-100,Math.min(100,n.affinity+Number(b.dataset.affinity)));persist();render();return}if(!b.dataset.speak)return;
 const actions={talk:'با این شخصیت گفتگو می‌کنم. ظاهر، لحن و پاسخ او را روایت کن و در پایان سه انتخاب مکالمه پیشنهاد بده.',persuade:'سعی می‌کنم او را متقاعد کنم. اگر نیاز به تاس است، مهارت و DC را اعلام کن و منتظر نتیجه بمان.',insight:'می‌خواهم نیت واقعی او را بررسی کنم. اگر آزمون Insight لازم است DC را اعلام کن؛ نتیجه تاس را جعل نکن.',quest:'از او درباره مأموریت‌ها، شایعات و خطرهای اطراف می‌پرسم.'};
 const input=$('#game-input');if(!input)return;input.value=`شخصیت حاضر: ${n.name}، نقش: ${n.role}، مکان ملاقات: ${n.location||'نامعلوم'}، وضعیت رابطه: ${mood(n.affinity)} (${n.affinity}). اطلاعات ثبت‌شده: ${(n.notes||'هنوز اطلاعاتی ندارم').slice(0,700)}. ${actions[b.dataset.speak]}`;tabs.querySelector('[data-adv-tab="story"]')?.click();input.focus();feedback('فرمان گفتگو آماده است؛ برای ارسال دکمه ادامه داستان را بزن.');};
 tabs.addEventListener('click',e=>{const b=e.target.closest('[data-adv-tab]');if(!b)return;const active=b===tab;panel.hidden=!active;if(active){['#game-story','#game-choices','#game-form','#adv-dialogue','#adv-battle','#adv-journal','#adv-inventory','#adv-world'].forEach(s=>{const p=$(s);if(p)p.hidden=true});tabs.querySelectorAll('[data-adv-tab]').forEach(x=>{x.classList.toggle('active',x===tab);x.setAttribute('aria-selected',String(x===tab))});render()}},true);
 $('#game-campaign')?.addEventListener('change',render);render();
})();
