/* Infinite Realms 16: tactical companion and connected travel planner. No Worker change. */
'use strict';(()=>{
const game=document.getElementById('game');if(!game)return;
const $=s=>game.querySelector(s),escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const CAMP=()=>$('#game-campaign')?.value||'none',HERO=()=>$('#game-hero')?.value||'none';
const STAGE='infinite-realms-stage10',RULES='infinite-realms-adventure7',KEY='infinite-realms-tactical16';
const load=(k,def={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')||def}catch{return def}};
const write=(k,v)=>{localStorage.setItem(k,JSON.stringify(v));game.dispatchEvent(new CustomEvent('ir:state-change'))};
const getWorld=()=>{const db=load(STAGE),c=db.campaigns?.[CAMP()];if(!c)return null;const map=c.maps?.[c.activeMap||'overworld'];return {c,map}};
const getRules=()=>{const db=load(RULES);return {db,s:db[CAMP()+'::'+HERO()]||null}};
const getBattle=()=>{const db=load(KEY),id=CAMP()+'::'+HERO();db[id]||={round:1,turn:1,phase:'ready',enemy:null,history:[]};return {db,id,s:db[id]}};
const saveBattle=x=>write(KEY,x.db);
const roll=n=>{const v=new Uint32Array(1),max=4294967296-(4294967296%n);do{crypto.getRandomValues(v)}while(v[0]>=max);return v[0]%n+1};
const box=document.createElement('section');box.id='ir16-root';box.innerHTML=`<button type="button" id="ir16-trigger" aria-haspopup="dialog" aria-expanded="false">⚔ <span>نبرد و سفر</span></button><div id="ir16-shade" hidden></div><section id="ir16-dialog" role="dialog" aria-modal="true" aria-label="نبرد و سفر" hidden><header><strong>⚔ فرماندهی ماجراجویی</strong><button id="ir16-close" type="button" aria-label="بستن">✕</button></header><nav><button data-view="combat" class="active">⚔ نبرد</button><button data-view="travel">🗺 سفر و مسیر</button></nav><div id="ir16-content"></div><p class="ir16-foot">تاس و منابع در مرورگر ثبت می‌شوند؛ نتیجه داستانی و جابه‌جایی نهایی فقط پس از تأیید راوی و بازیکن اعمال می‌شود.</p></section>`;game.append(box);
const trigger=$('#ir16-trigger'),dialog=$('#ir16-dialog'),shade=$('#ir16-shade'),content=$('#ir16-content');let view='combat',focus=null;
function show(){focus=document.activeElement;dialog.hidden=shade.hidden=false;trigger.setAttribute('aria-expanded','true');render();$('#ir16-close').focus()}
function hide(){dialog.hidden=shade.hidden=true;trigger.setAttribute('aria-expanded','false');focus?.focus?.()}
function note(t){const x=document.createElement('p');x.className='ir16-message';x.textContent=t;content.prepend(x)}
function submitToDM(t){const input=$('#game-input');if(!input){note('ابتدا کمپین را شروع کن.');return}input.value=t;hide();$('#game-form')?.requestSubmit()}
function render(){dialog.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));view==='combat'?combat():travel()}
function combat(){const {s:r}=getRules(),b=getBattle().s;content.innerHTML=`<div class="ir16-summary"><span>راند <b>${b.round}</b></span><span>نوبت <b>${b.turn}</b></span><span>♥ ${r?`${r.hp}/${r.max}`:'برگه قهرمان تنظیم نشده'}</span><span>⛨ AC ${r?.ac??'—'}</span></div><div class="ir16-grid"><button data-action="attack">⚔ حمله با تاس ۲۰</button><button data-action="defend">🛡 دفاع / Dodge</button><button data-action="skill">🎯 بررسی مهارت</button><button data-action="next">↻ نوبت بعدی</button></div><form id="ir16-damage"><label>آسیب دریافتی <input type="number" name="damage" min="0" max="999" value="0" required></label><button>ثبت آسیب روی HP</button></form><form id="ir16-heal"><label>درمان <input type="number" name="heal" min="0" max="999" value="0" required></label><button>ثبت درمان</button></form><div class="ir16-log"><strong>گزارش نبرد</strong>${b.history.slice(0,12).map(x=>`<p>${escapeHTML(x)}</p>`).join('')||'<p>هنوز اقدامی ثبت نشده.</p>'}</div><button data-action="reset" class="ir16-subtle">شروع نبرد جدید</button>`}
function travel(){const w=getWorld();if(!w?.map){content.innerHTML='<p>ابتدا یک کمپین فعال انتخاب کن و اطلس بازی را باز کن.</p>';return}const {c,map}=w,active=map.places?.find(p=>p.id===map.active),known=(map.places||[]).filter(p=>p.known);content.innerHTML=`<div class="ir16-current">📍 مکان فعلی: <strong>${escapeHTML(active?.name||'نامشخص')}</strong><small>نقشه: ${escapeHTML(c.activeMap||'overworld')}</small></div><div class="ir16-route" role="group" aria-label="مسیرهای مکان‌های کشف‌شده">${known.map(p=>{const d=active?Math.round(Math.hypot((p.x-active.x)*1.2,(p.y-active.y)*1.2)):0;return `<button data-destination="${escapeHTML(p.id)}" ${p.id===map.active?'disabled':''}><span>${p.id===map.active?'📍':'◇'} ${escapeHTML(p.name)}</span><small>${p.id===map.active?'اینجا هستی':`فاصله تقریبی نقشه: ${d} واحد`}</small></button>`}).join('')}</div><p class="ir16-tip">فاصله، مقیاس تصویری نقشه است؛ زمان سفر و خطرها را راوی تعیین می‌کند. مکان‌های کشف‌نشده در اطلس اصلی قابل مشاهده‌اند.</p><button data-action="atlas">بازکردن اطلس کامل</button>`}
function log(b,t){b.history.unshift('راند '+b.round+'، نوبت '+b.turn+': '+t);b.history=b.history.slice(0,30)}
trigger.onclick=show;$('#ir16-close').onclick=hide;shade.onclick=hide;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.hidden)hide()});
dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();return}const a=b.dataset.action;if(a){if(a==='atlas'){hide();$('#a10-fab')?.click();setTimeout(()=>game.querySelector('[data-open="map"]')?.click(),0);return}const x=getBattle(),s=x.s;if(a==='reset'){if(!confirm('گزارش نبرد فعلی پاک شود؟'))return;x.db[x.id]={round:1,turn:1,phase:'ready',history:[]};saveBattle(x);render();return}if(a==='next'){s.turn++;if(s.turn>2){s.turn=1;s.round++}s.phase='ready';log(s,'نوبت بعدی');saveBattle(x);render();return}if(a==='attack'){if(s.phase!=='ready'){note('در این نوبت اقدام اصلی ثبت شده؛ ابتدا نوبت بعدی را بزن.');return}const {s:r}=getRules(),bonus=r?Math.floor(((r.stats?.str??10)-10)/2)+(r.prof||2):0,n=roll(20);s.phase='acted';log(s,'حمله: '+n+' + '+bonus+' = '+(n+bonus));saveBattle(x);render();submitToDM('برای حمله تاس واقعی d20 من '+n+' شد و اصلاح‌کننده پایه قدرت و مهارت '+bonus+' است؛ جمع '+(n+bonus)+'. با توجه به دشمن، تجهیزات و شرایط، اصابت و آسیب را مشخص کن.');return}if(a==='defend'){if(s.phase!=='ready'){note('اقدام اصلی این نوبت ثبت شده.');return}s.phase='acted';log(s,'دفاع / Dodge');saveBattle(x);render();submitToDM('در نوبت فعلی اقدام Dodge انجام می‌دهم. مزیت‌های دفاعی و حملات دشمن را مطابق قوانین اعمال کن.');return}if(a==='skill'){const n=roll(20);log(s,'بررسی مهارت: d20='+n);saveBattle(x);render();submitToDM('برای بررسی مهارت d20 واقعی من '+n+' شد. با توجه به مهارت قهرمان و درجه سختی نتیجه را محاسبه کن.');return}}if(b.dataset.destination){const w=getWorld(),p=w?.map?.places?.find(p=>p.id===b.dataset.destination);if(!p||!p.known||p.id===w.map.active)return;const current=w.map.places.find(x=>x.id===w.map.active);submitToDM('از «'+(current?.name||'مکان فعلی')+'» قصد سفر به «'+p.name+'» در نقشه '+w.c.activeMap+' را دارم. مسیر، خطرها و مدت را توصیف کن. فقط اگر واقعاً به مقصد رسیدم رویداد travel برای تأیید پیشنهاد بده؛ فعلاً موقعیت من را تغییر نده.');}});
dialog.addEventListener('submit',e=>{if(!['ir16-damage','ir16-heal'].includes(e.target.id))return;e.preventDefault();const damage=e.target.id==='ir16-damage',n=Number(new FormData(e.target).get(damage?'damage':'heal'));if(!Number.isInteger(n)||n<0||n>999)return note('عدد نامعتبر است');const {db,s}=getRules();if(!s)return note('ابتدا برگه قهرمان را در بخش قوانین تنظیم کن.');if(!confirm((damage?'ثبت آسیب ':'ثبت درمان ')+n+' روی قهرمان فعلی؟'))return;if(damage){const absorbed=Math.min(s.temp||0,n);s.temp=(s.temp||0)-absorbed;s.hp=Math.max(0,s.hp-(n-absorbed))}else s.hp=Math.min(s.max,s.hp+n);write(RULES,db);const x=getBattle();log(x.s,(damage?'آسیب ':'درمان ')+n+'؛ HP='+s.hp);saveBattle(x);render()});
window.addEventListener('ir:cloud-restored',()=>{if(!dialog.hidden)render()});game.addEventListener('ir:state-change',()=>{if(!dialog.hidden&&view==='travel')render()});$('#game-campaign')?.addEventListener('change',()=>{if(!dialog.hidden)render()});$('#game-hero')?.addEventListener('change',()=>{if(!dialog.hidden)render()});
})();
