/* Infinite Realms: playable campaign view. No framework; keeps existing editor intact. */
'use strict';
(()=>{
const GAME_API='https://dandd.bytelab.workers.dev';
const K='infinite-realms-game-v1';
let g;try{g=JSON.parse(localStorage.getItem(K)||'{}')}catch{g={}}
g.token ||= Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
g.states ||= {};g.current ||= '';g.api ||= GAME_API;
const store=()=>localStorage.setItem(K,JSON.stringify(g));store();
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const page=document.createElement('section');page.id='game';page.className='page';
page.innerHTML=`<div class="game-top"><div><span class="game-eyebrow">✦ INFINITE REALMS · THE ADVENTURE</span><h2>دروازه قلمروها</h2><p>داستانت را زندگی کن؛ تصمیم بگیر، تاس بینداز و سرنوشتت را تغییر بده.</p></div><span id="game-cloud" class="game-cloud">◌ ذخیره محلی</span></div>
<div class="game-toolbar"><label>ماجراجویی<select id="game-campaign"></select></label><label>قهرمان<select id="game-hero"></select></label><button id="game-begin" class="primary">⚔ ورود به ماجراجویی</button><button id="game-sync" class="outline">☁ بازیابی از ابر</button></div>
<div class="game-layout"><div class="game-main"><div class="game-scene"><div class="game-scene-shade"><span class="game-chapter" id="game-chapter">فصل نخست</span><h3 id="game-scene-title">افسانه‌ای در انتظار توست</h3><p id="game-scene-desc">یک کمپین و قهرمان انتخاب کن تا دروازه قلمروها گشوده شود.</p></div></div>
<div class="game-story" id="game-story" aria-live="polite"><div class="game-empty">⚜<p>هر انتخاب، بخشی از افسانه تو خواهد شد.</p></div></div>
<div id="game-choices" class="game-choices"><button class="game-choice" data-action="به اطراف نگاه می‌کنم و محیط را بررسی می‌کنم.">◈ بررسی محیط</button><button class="game-choice" data-action="با نزدیک‌ترین شخصیت گفتگو می‌کنم.">♜ گفتگو</button><button class="game-choice" data-action="محتاطانه به جلو حرکت می‌کنم.">➤ حرکت به جلو</button></div>
<form id="game-form" class="game-form"><label for="game-input">اقدام بعدی تو چیست؟</label><div class="game-compose"><textarea id="game-input" maxlength="3500" rows="2" placeholder="مثلاً شمشیرم را بیرون می‌کشم و به سوی دروازه می‌روم..."></textarea><button id="game-send" class="primary" type="submit">ادامه داستان ✦</button></div><span id="game-feedback" role="status">برای شروع، وارد ماجراجویی شو.</span></form></div>
<aside class="game-side"><div class="game-widget"><div class="game-widget-title">♙ برگه قهرمان</div><div id="game-hero-card" class="game-hero-card">هنوز قهرمانی انتخاب نشده است.</div></div>
<div class="game-widget"><div class="game-widget-title">⚄ تاس سرنوشت</div><div id="game-die" class="game-die">20</div><div class="game-dice-row"><button data-roll="4">D4</button><button data-roll="6">D6</button><button data-roll="8">D8</button><button data-roll="10">D10</button><button data-roll="12">D12</button><button data-roll="20">D20</button></div><p id="game-roll-result" class="game-dim">تاس بینداز تا سرنوشتت مشخص شود.</p><button id="game-send-roll" class="outline">اعلام نتیجه به DM</button></div>
<div class="game-widget"><div class="game-widget-title">☷ دفتر ماجراجویی</div><p id="game-journal" class="game-dim">وقایع بازی اینجا ثبت می‌شوند.</p><button id="game-export" class="outline">↓ پشتیبان بازی</button></div></aside></div>`;
document.querySelector('main.main').insertBefore(page,document.querySelector('main.main footer'));
const b=document.createElement('button');b.dataset.page='game';b.innerHTML='⚔ <span>شروع بازی</span>';nav.prepend(b);pages.game='قلمرو ماجراجویی';
const el=id=>document.getElementById(id), campaign=()=>db.campaigns.find(c=>c.id===el('game-campaign').value),hero=()=>db.characters.find(c=>c.id===el('game-hero').value);
const state=()=>{const c=campaign();if(!c)return null;return g.states[c.id] ||= {messages:[],chapter:1,heroId:'',lastRoll:null,updated:0}};
function refresh(){let cId=el('game-campaign').value||g.current;el('game-campaign').innerHTML=db.campaigns.length?db.campaigns.map(c=>`<option value="${safe(c.id)}">${safe(c.title)}</option>`).join(''):'<option value="">ابتدا در سناریوساز یک کمپین بساز</option>';if(db.campaigns.some(c=>c.id===cId))el('game-campaign').value=cId;let s=state();el('game-hero').innerHTML=db.characters.length?db.characters.map(h=>`<option value="${safe(h.id)}">${safe(h.name)} · ${safe(h.klass)}</option>`).join(''):'<option value="">ابتدا یک قهرمان بساز</option>';if(s?.heroId&&db.characters.some(h=>h.id===s.heroId))el('game-hero').value=s.heroId;render()}
function render(){let c=campaign(),s=state(),h=hero();el('game-scene-title').textContent=c?.title||'افسانه‌ای در انتظار توست';el('game-scene-desc').textContent=c?.hook||'برای آغاز یک کمپین انتخاب کن.';el('game-chapter').textContent=`فصل ${s?.chapter||1} · ${c?.setting||'قلمرو ناشناخته'}`;el('game-hero-card').innerHTML=h?`<div class="game-avatar">♜</div><strong>${safe(h.name)}</strong><p>${safe(h.species)} · ${safe(h.klass)} · سطح ${Number(h.level)||1}</p><div class="game-hp"><span>♥ جان</span><b>${Number(h.hp)||0} HP</b></div><div class="game-hp"><span>⛨ زره</span><b>${Number(h.ac)||10} AC</b></div>`:'قهرمانت را از بخش شخصیت‌ها بساز.';
el('game-story').innerHTML=s?.messages.length?s.messages.map(m=>`<article class="game-entry ${m.role==='user'?'game-player':'game-narrator'}"><div class="game-entry-label">${m.role==='user'?'♙ تصمیم تو':'✦ راوی قلمروها'}</div><p>${safe(m.content)}</p></article>`).join(''):'<div class="game-empty">⚜<p>برای شروع ماجراجویی دکمه ورود را بزن.</p></div>';
el('game-journal').textContent=s?.messages.length?`آخرین اتفاق: ${s.messages.filter(m=>m.role==='assistant').slice(-1)[0]?.content.slice(0,230)||'در انتظار روایت...'}`:'هنوز رویدادی ثبت نشده است.';el('game-story').scrollTop=el('game-story').scrollHeight;el('game-cloud').textContent=s?.updated?'✓ آخرین ذخیره '+new Date(s.updated).toLocaleTimeString('fa-IR'):'◌ آماده شروع';}
function cloudStatus(t){el('game-cloud').textContent=t}
// Version 14: one cloud snapshot per campaign, preserving legacy story and RPG stores.
const RPG_KEYS=['infinite-realms-stage10','infinite-realms-adventure7','infinite-realms-adventure3','infinite-realms-adventure4','infinite-realms-adventure5'];
function snapshot(c){const stores={};for(const key of RPG_KEYS){try{const all=JSON.parse(localStorage.getItem(key)||'{}');const part=key==='infinite-realms-adventure7'?Object.fromEntries(Object.entries(all).filter(([id])=>id===c.id||id.startsWith(c.id+'::'))):all.campaigns?.[c.id];if(part!==undefined)stores[key]=part}catch{}}return {format:'ir-campaign-v14',story:state(),stores,created:Date.now()}}
function restoreSnapshot(c,data){if(!data||typeof data!=='object')throw Error('فایل ذخیره نامعتبر است');const packed=data.format==='ir-campaign-v14';const story=packed?data.story:data;if(!story||!Array.isArray(story.messages))throw Error('داستان ذخیره‌شده معتبر نیست');const updates=[];if(packed){for(const [key,part] of Object.entries(data.stores||{})){if(!RPG_KEYS.includes(key)||!part||typeof part!=='object')continue;const all=JSON.parse(localStorage.getItem(key)||'{}');if(key==='infinite-realms-adventure7'){if(part&&Object.keys(part).some(id=>id===c.id||id.startsWith(c.id+'::'))){for(const [id,value] of Object.entries(part)){if(id===c.id||id.startsWith(c.id+'::'))all[id]=value}}else all[c.id]=part;}else{all.campaigns||={};all.campaigns[c.id]=part}updates.push([key,JSON.stringify(all)])}}const old=JSON.stringify(g.states[c.id]);try{for(const [key,value] of updates)localStorage.setItem(key,value);g.states[c.id]=story;store()}catch(e){g.states[c.id]=JSON.parse(old||'null');throw e}page.dispatchEvent(new CustomEvent('ir:state-change'));window.dispatchEvent(new Event('ir:cloud-restored'));render()}
async function cloudSave(){let c=campaign(),s=state();if(!c||!s)return;store();cloudStatus('◌ در حال ذخیره...');try{const r=await fetch(g.api+'/api/game/state',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+g.token},body:JSON.stringify({campaignId:c.id,state:snapshot(c)})});if(!r.ok)throw Error('sync');cloudStatus('☁ داستان و وضعیت RPG ذخیره شد')}catch{cloudStatus('◌ ذخیره محلی؛ ابر در دسترس نیست')}}
async function cloudLoad(){let c=campaign();if(!c)return;cloudStatus('◌ بازیابی...');try{const r=await fetch(g.api+'/api/game/state?campaignId='+encodeURIComponent(c.id),{headers:{Authorization:'Bearer '+g.token}});if(!r.ok)throw Error('sync');const data=await r.json();if(data.state){if(!confirm('بازیابی ابر، داستان و وضعیت ذخیره‌شده این کمپین را جایگزین می‌کند. ادامه می‌دهی؟'))return;restoreSnapshot(c,data.state);cloudStatus(data.state.format==='ir-campaign-v14'?'☁ بازیابی کامل انجام شد':'☁ نسخه قدیمی: فقط داستان بازیابی شد')}else cloudStatus('نسخه ابری هنوز موجود نیست')}catch(e){cloudStatus('بازیابی ممکن نشد: '+e.message)}}
let busy=false,lastRoll=null;let syncTimer;page.addEventListener('ir:state-change',()=>{clearTimeout(syncTimer);syncTimer=setTimeout(()=>{if(campaign()&&g.states[campaign().id]?.messages?.length)cloudSave()},1800)});
async function act(text){let c=campaign(),h=hero(),s=state();if(!c)return toast('اول یک کمپین بساز');if(!h)return toast('اول یک شخصیت بساز');if(busy)return;busy=true;el('game-send').disabled=true;el('game-feedback').textContent='✦ راوی در حال خلق ادامه داستان است...';const history=s.messages.slice(-16).map(m=>({role:m.role,content:m.content}));const irState=(()=>{try{const d=JSON.parse(localStorage.getItem('infinite-realms-stage10')||'{}').campaigns?.[c.id];const rpgHero=d?.heroes?.[h.id];return JSON.stringify({inventory:rpgHero?.items?.map(i=>({name:i.name,count:i.count,equipped:!!i.equipped})),gold:rpgHero?.gold||0,learned:rpgHero?.learned||[],map:d?.activeMap,location:d?.maps?.[d?.activeMap]?.places?.find(p=>p.id===d?.maps?.[d?.activeMap]?.active)?.name,abilities:rpgHero?.spells||[],rules:(()=>{try{const r=JSON.parse(localStorage.getItem('infinite-realms-adventure7')||'{}');const x=r[c.id+'::'+h.id]||r[c.id]||{};return {hp:x.hp,max:x.max,ac:x.ac,slots:x.slots,conditions:x.conditions}}catch{return {}}})(),hp:(()=>{try{const r=JSON.parse(localStorage.getItem("infinite-realms-adventure7")||"{}");return (r[c.id+'::'+h.id]||r[c.id])?.hp??null}catch{return null}})()}).slice(0,2600)}catch{return '{}'}})();const context=`تو راوی تعاملی بازی فانتزی D&D هستی. فقط به فارسی روان و سینمایی پاسخ بده. هر نوبت ۲ تا ۴ پاراگراف کوتاه و در پایان دقیقاً سه گزینه کوتاه به صورت «۱) ... ۲) ... ۳) ...» ارائه کن. انتخاب آزاد بازیکن همیشه مجاز است. به جای بازیکن تصمیم نگیر و نتیجه تاس را جعل نکن؛ هنگام نیاز نوع تاس و DC را اعلام کن و منتظر نتیجه بمان. رویدادهای قبلی را به یاد بسپار. کمپین: ${JSON.stringify({title:c.title,setting:c.setting,genre:c.genre,hook:c.hook,notes:c.notes}).slice(0,4000)}. قهرمان: ${JSON.stringify({name:h.name,klass:h.klass,species:h.species,level:h.level,hp:h.hp,ac:h.ac})}. حافظه کمپین: ${String(p3.memories[c.id]||'').slice(0,4000)}. وضعیت ثبت‌شده و معتبر بازی: ${irState}. هرگز بدون اقدام بازیکن آیتم یا توانایی اعطا نکن. اگر رویداد واقعی قابل ثبت رخ داد، بعد از سه انتخاب در پایان پاسخ، فقط یک بلوک جداگانه با ساختار <game_state>{"events":[{"type":"gain_item","name":"نام آیتم","amount":1}]}</game_state> بنویس. رویدادهای مجاز: gain_item, lose_item, gain_gold, lose_gold, learn_ability, discover_place (map: overworld/underworld/wilds و place), travel (map و place؛ فقط پس از ورود قطعی شخصیت به مقصد), damage, heal, quest_note. فقط رویدادهای قطعی رخ‌داده را پیشنهاد بده، نه پیامدهای احتمالی یا اتفاقاتی که به تاس نیاز دارند. حداکثر ۵ رویداد. تمام رویدادها قبل از اعمال نیازمند تأیید بازیکن هستند.`;
try{const r=await fetch(g.api+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:context},...history,{role:'user',content:text}]})});const data=await r.json();if(!r.ok)throw Error(data.error||'ارتباط با AI برقرار نشد');if(!data.message)throw Error('پاسخی دریافت نشد');let narrative=data.message,events=[];const block=narrative.match(/<game_state>([\s\S]{0,3500}?)<\/game_state>/i);if(block){try{const proposed=JSON.parse(block[1]);if(Array.isArray(proposed.events))events=proposed.events.slice(0,5)}catch{}narrative=narrative.replace(block[0],'').trim()}s.messages.push({role:'user',content:text},{role:'assistant',content:narrative});game.dispatchEvent(new CustomEvent('ir:ai-turn',{detail:{campaignId:c.id,heroId:h.id,events}}));s.messages=s.messages.slice(-60);s.updated=Date.now();g.current=c.id;s.heroId=h.id;store();render();el('game-input').value='';el('game-feedback').textContent='نوبت توست؛ یک گزینه انتخاب کن یا اقدام دلخواهت را بنویس.';const matches=[...narrative.matchAll(/(?:^|\n)\s*[۱۱۲۳1-3][)\.\-]\s*([^\n]{5,100})/g)].slice(-3);if(matches.length)el('game-choices').innerHTML=matches.map((m,i)=>`<button class="game-choice" data-action="${safe(m[1])}">✧ ${safe(m[1])}</button>`).join('');await cloudSave();}catch(e){game.dispatchEvent(new CustomEvent('ir:ai-error',{detail:{campaignId:c.id}}));el('game-feedback').textContent='خطا: '+e.message+'؛ دوباره تلاش کن.'}finally{busy=false;el('game-send').disabled=false}}
nav.querySelector('[data-page="game"]').addEventListener('click',()=>{go('game');refresh()});document.querySelector('[data-page="dashboard"]').insertAdjacentElement('beforebegin',document.createElement('span')); // preserve original navigation
el('game-campaign').addEventListener('change',()=>{g.current=el('game-campaign').value;store();refresh()});el('game-hero').addEventListener('change',()=>{let s=state();if(s){s.heroId=el('game-hero').value;store()}render()});
el('game-begin').addEventListener('click',()=>{let s=state();if(!s)return toast('کمپین بساز');if(s.messages.length)return toast('بازی ادامه دارد؛ اقدام بعدی را انتخاب کن');act('ماجراجویی را با یک صحنه آغازین پرهیجان شروع کن. مکان، یک شخصیت مرموز و سه انتخاب مهم را معرفی کن.')});
el('game-form').addEventListener('submit',e=>{e.preventDefault();let v=el('game-input').value.trim();if(v)act(v)});el('game-choices').addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(b)act(b.dataset.action)});
el('game-sync').addEventListener('click',cloudLoad);document.querySelectorAll('[data-roll]').forEach(b=>b.addEventListener('click',()=>{let n=Number(b.dataset.roll),v=crypto.getRandomValues(new Uint32Array(1))[0]%n+1;lastRoll={n,v};el('game-die').textContent=v;el('game-die').classList.remove('game-die-animate');void el('game-die').offsetWidth;el('game-die').classList.add('game-die-animate');el('game-roll-result').textContent=`D${n} → ${v}`;}));el('game-send-roll').addEventListener('click',()=>{if(!lastRoll)return toast('اول تاس بینداز');act(`نتیجه تاس من D${lastRoll.n} برابر ${lastRoll.v} شد. با توجه به این نتیجه داستان را ادامه بده.`)});
el('game-export').addEventListener('click',()=>{let c=campaign();if(!c)return;const blob=new Blob([JSON.stringify({campaign:c,snapshot:snapshot(c),exported:new Date().toISOString()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='infinite-realms-game-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)});
// Prefer game page on first visit while retaining the original editor and all its features.
refresh();go('game');
})();