/* Presentation-only immersive layer. Does not replace existing game logic or AI backend. */
'use strict';
(()=>{
 const game=document.getElementById('game');if(!game)return;
 const scene=game.querySelector('.game-scene'),story=game.querySelector('#game-story'),feedback=game.querySelector('#game-feedback');
 const hud=document.createElement('div');hud.className='game-hud';hud.innerHTML=`<button class="hud-chip" id="im-focus" aria-pressed="false" title="حذف پنل‌ها و تمرکز روی بازی">⛶ حالت سینمایی</button><button class="hud-chip" id="im-sound" aria-pressed="false" title="صدای محیط؛ فقط با کلیک فعال می‌شود">♫ صدای محیط</button><button class="hud-chip" id="im-dice" title="پرتاب تاس D20">⚄ تاس سریع D20</button><button class="hud-chip" id="im-journal" title="رفتن به دفتر وقایع">☷ دفتر وقایع</button><span class="game-turn-indicator" id="im-status" aria-live="polite">✦ منتظر تصمیم تو</span>`;
 game.querySelector('.game-layout').before(hud);
 const overlay=document.createElement('div');overlay.className='game-screen-overlay';overlay.setAttribute('aria-hidden','true');game.append(overlay);
 const dock=document.createElement('div');dock.className='game-immersive-dock';dock.innerHTML='<button id="im-next">✦ انتخاب بعدی</button><button id="im-action">⚔ اقدام آزاد</button>';game.querySelector('.game-layout').after(dock);
 const $=id=>document.getElementById(id);let audio=null,master=null;
 function announce(message){let old=game.querySelector('.game-toast');if(old)old.remove();const t=document.createElement('div');t.className='game-toast';t.textContent=message;t.setAttribute('role','status');game.append(t);setTimeout(()=>t.remove(),2600)}
 function setFocus(on){document.body.classList.toggle('immersive-focus',on);$('im-focus').setAttribute('aria-pressed',String(on));$('im-focus').textContent=on?'⊞ خروج از حالت سینمایی':'⛶ حالت سینمایی';localStorage.setItem('infinite-realms-cinematic',on?'1':'0')}
 $('im-focus').onclick=()=>setFocus(!document.body.classList.contains('immersive-focus'));
 if(localStorage.getItem('infinite-realms-cinematic')==='1')setFocus(true);
 $('im-dice').onclick=()=>{const die=game.querySelector('[data-roll="20"]');if(die){die.click();game.querySelector('#game-die')?.scrollIntoView({behavior:'smooth',block:'center'});announce('⚄ تاس بیست‌وجهی پرتاب شد')}};
 $('im-journal').onclick=()=>game.querySelector('#game-journal')?.scrollIntoView({behavior:'smooth',block:'center'});
 $('im-next').onclick=()=>{const choice=game.querySelector('.game-choice');if(choice){choice.scrollIntoView({behavior:'smooth',block:'center'});choice.focus()}else announce('منتظر پاسخ راوی باش')};
 $('im-action').onclick=()=>{game.querySelector('#game-input')?.scrollIntoView({behavior:'smooth',block:'center'});game.querySelector('#game-input')?.focus()};
 async function toggleSound(){if(audio){await audio.close();audio=null;master=null;$('im-sound').textContent='♫ صدای محیط';$('im-sound').setAttribute('aria-pressed','false');return}const AC=window.AudioContext||window.webkitAudioContext;if(!AC){announce('مرورگر از صدای محیط پشتیبانی نمی‌کند');return}try{audio=new AC();master=audio.createGain();master.gain.value=.018;master.connect(audio.destination);[110,164.81,220].forEach((freq,i)=>{const o=audio.createOscillator(),gain=audio.createGain();o.type='sine';o.frequency.value=freq;gain.gain.value=i===0?.42:.13;o.connect(gain).connect(master);o.start()});await audio.resume();$('im-sound').textContent='♫ قطع صدا';$('im-sound').setAttribute('aria-pressed','true')}catch{announce('صدای محیط فعال نشد')}}
 $('im-sound').onclick=toggleSound;
 function theme(){const text=((game.querySelector('#game-scene-desc')?.textContent||'')+' '+(game.querySelector('#game-scene-title')?.textContent||'')+' '+(story.querySelector('.game-narrator:last-of-type')?.textContent||'')).slice(-1800);scene.classList.remove('theme-forest','theme-dungeon','theme-desert','theme-battle');const patterns=[['theme-battle',/مبارزه|نبرد|خون|دشمن|اژدها|attack|battle/i],['theme-forest',/جنگل|درخت|مه|forest|woods/i],['theme-dungeon',/سیاهچال|زندان|دژ|غار|قلعه|dungeon|cave/i],['theme-desert',/بیابان|صحرا|شن|desert/i]];const match=patterns.find(([,re])=>re.test(text));if(match)scene.classList.add(match[0]);const hero=game.querySelector('#game-hero-card');const hpText=hero?.textContent||'';const hp=hpText.match(/(\d+)\s*HP/i);overlay.classList.toggle('danger',!!hp&&Number(hp[1])<=3);$('im-status').textContent=feedback?.textContent?.includes('در حال خلق')?'◌ راوی در حال نوشتن سرنوشت...':'✦ نوبت توست'}
 const observer=new MutationObserver(()=>{if(game.classList.contains('active'))theme()});observer.observe(story,{childList:true,subtree:false});if(feedback)observer.observe(feedback,{childList:true,characterData:true,subtree:true});game.querySelector('#game-campaign')?.addEventListener('change',()=>setTimeout(theme,0));theme();
 document.addEventListener('keydown',e=>{if(!game.classList.contains('active')||e.target.closest('input,textarea,select,[contenteditable]'))return;if(e.key==='Escape'&&document.body.classList.contains('immersive-focus'))setFocus(false);if(e.key.toLowerCase()==='r')$('im-dice').click();if(['1','2','3'].includes(e.key)){const choice=game.querySelectorAll('.game-choice')[Number(e.key)-1];if(choice&&!choice.disabled)choice.click()}});
})();
