'use strict';
/* Optional local AI DM. Existing game works without the server or a model. */
const P3KEY='infinite-realms-phase3';
let p3;try{p3=JSON.parse(localStorage.getItem(P3KEY)||'{}')}catch{p3={}}
p3.chats ||= {};p3.memories ||= {};p3.model ||= 'qwen2.5:3b';p3.apiUrl ||= 'https://dandd.bytelab.workers.dev';
const p3save=()=>localStorage.setItem(P3KEY,JSON.stringify(p3));
const dmHost=document.createElement('section');dmHost.id='ai-dm';dmHost.className='page';
dmHost.innerHTML=`<div class="section-head"><div><h2>✦ Dungeon Master هوشمند</h2><p class="muted">مدل آنلاین فعال است؛ کمپین و روایت را اینجا مدیریت کن.</p></div></div>
<div class="panel"><label>آدرس سرور AI آنلاین<input id="dm-api-url" type="url" placeholder="https://your-worker.workers.dev"></label><div class="form-grid mini"><label>کمپین<select id="dm-campaign"></select></label><label>مدل آنلاین<select id="dm-model"><option value="qwen2.5:3b">qwen2.5:3b</option></select></label></div><div class="actions"><button class="outline" id="dm-health">بررسی اتصال</button><span class="muted" id="dm-status" role="status">برای اتصال به سرور آنلاین، بررسی اتصال را بزن.</span></div></div>
<div class="panel"><h3>حافظه کمپین</h3><label>وقایع و اطلاعاتی که DM باید به یاد داشته باشد<textarea id="dm-memory" rows="4" maxlength="8000" placeholder="مثلاً: گروه با اژدها پیمان بسته است..."></textarea></label><div class="actions"><button class="outline" id="dm-save-memory">ذخیره حافظه</button><button class="outline" id="dm-from-story">افزودن وقایع و NPCهای ویرایشگر</button></div></div>
<div class="panel"><h3>میز روایت</h3><div id="dm-chat" class="dm-chat" aria-live="polite"></div><form id="dm-form"><label>پیام به Dungeon Master<textarea id="dm-prompt" rows="3" required maxlength="3500" placeholder="بازیکنان وارد قلعه شدند؛ چه می‌بینند؟"></textarea></label><div class="actions"><button class="primary" id="dm-send" type="submit">ارسال به DM ✦</button><button class="outline" id="dm-intro" type="button">شروع ماجراجویی</button><button class="danger-outline" id="dm-clear" type="button">پاک‌کردن گفت‌وگو</button></div></form><p class="muted small">متن پاسخ مدل ممکن است خطا داشته باشد. نتیجه تاس، HP و قوانین را از موتور بازی بررسی کن. تاریخچه در مرورگر ذخیره می‌شود.</p></div>`;
document.querySelector('main.main').insertBefore(dmHost,document.querySelector('main.main footer'));
const dmNav=document.createElement('button');dmNav.dataset.page='ai-dm';dmNav.innerHTML='✦ <span>DM هوشمند</span>';nav.append(dmNav);pages['ai-dm']='Dungeon Master هوشمند';dmNav.addEventListener('click',()=>{go('ai-dm');dmRefresh()});
const dmEl=id=>document.getElementById(id);
const dmCurrent=()=>dmEl('dm-campaign').value;
const dmApi=()=>{const v=dmEl('dm-api-url').value.trim().replace(/\/+$/,'');if(!v)return '';const u=new URL(v);if(u.protocol!=='https:' && !['localhost','127.0.0.1'].includes(u.hostname))throw Error('HTTPS لازم است');return u.origin+u.pathname.replace(/\/+$/,'')};
dmEl('dm-api-url').value=p3.apiUrl;dmEl('dm-api-url').addEventListener('change',()=>{try{p3.apiUrl=dmApi();p3save();dmEl('dm-status').textContent='آدرس ذخیره شد'}catch(e){dmEl('dm-status').textContent=e.message}});
function dmRefresh(){const old=dmCurrent();dmEl('dm-campaign').innerHTML=db.campaigns.length?db.campaigns.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join(''):'<option value="">ابتدا یک کمپین ذخیره کن</option>';if(db.campaigns.some(c=>c.id===old))dmEl('dm-campaign').value=old;dmLoad()}
function dmLoad(){const id=dmCurrent();dmEl('dm-memory').value=p3.memories[id]||'';const history=p3.chats[id]||[];dmEl('dm-chat').innerHTML=history.length?history.map(m=>`<div class="dm-message ${m.role==='user'?'dm-user':'dm-assistant'}"><strong>${m.role==='user'?'بازیکن':'Dungeon Master'}</strong><p>${esc(m.content)}</p></div>`).join(''):'<p class="muted">برای شروع، یک کمپین انتخاب کن و پیامت را بنویس.</p>';dmEl('dm-chat').scrollTop=dmEl('dm-chat').scrollHeight}
dmEl('dm-campaign').addEventListener('change',dmLoad);
dmEl('dm-save-memory').addEventListener('click',()=>{if(!dmCurrent())return toast('ابتدا کمپین بساز');p3.memories[dmCurrent()]=dmEl('dm-memory').value;p3save();toast('حافظه ذخیره شد')});
dmEl('dm-from-story').addEventListener('click',()=>{const id=dmCurrent();if(!id)return toast('ابتدا کمپین بساز');const story=p2.stories[id];if(!story)return toast('ابتدا در ویرایشگر کمپین، صحنه یا NPC ثبت کن');const summary=JSON.stringify(story).slice(0,4500);dmEl('dm-memory').value=(dmEl('dm-memory').value+'\nاطلاعات ویرایشگر: '+summary).slice(-8000);p3.memories[id]=dmEl('dm-memory').value;p3save();toast('اطلاعات ویرایشگر افزوده شد')});
async function dmHealth(){dmEl('dm-status').textContent='در حال بررسی...';try{const r=await fetch(dmApi()+'/api/health');if(!r.ok)throw Error('server');const data=await r.json();if(!data.connected)throw Error('ollama');dmEl('dm-model').innerHTML=data.models.length?data.models.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join(''):'<option value="">مدلی نصب نشده</option>';if(data.models.includes(p3.model))dmEl('dm-model').value=p3.model;else if(data.models.length){dmEl('dm-model').value=data.models[0];p3.model=data.models[0];p3save()}dmEl('dm-status').textContent=data.models.length?'سرور آنلاین متصل است؛ '+data.models.length+' مدل یافت شد.':'سرور آنلاین متصل است؛ ابتدا یک مدل دانلود کن.';return data.models.length>0}catch{dmEl('dm-status').textContent='اتصال برقرار نیست؛ آدرس Worker و کلید Groq را بررسی کن.';return false}}
dmEl('dm-health').addEventListener('click',dmHealth);
dmEl('dm-model').addEventListener('change',()=>{p3.model=dmEl('dm-model').value;p3save()});
dmEl('dm-intro').addEventListener('click',()=>{dmEl('dm-prompt').value='ماجراجویی را با یک صحنه آغازین جذاب، سه گزینه برای تصمیم‌گیری و یک آزمون مهارت مناسب شروع کن. نتیجه تاس را خودت تعیین نکن.';dmEl('dm-prompt').focus()});
dmEl('dm-clear').addEventListener('click',()=>{if(!dmCurrent()||!confirm('گفت‌وگوی این کمپین پاک شود؟'))return;p3.chats[dmCurrent()]=[];p3save();dmLoad()});
dmEl('dm-form').addEventListener('submit',async e=>{e.preventDefault();const id=dmCurrent(),c=db.campaigns.find(c=>c.id===id),message=dmEl('dm-prompt').value.trim();if(!c)return toast('ابتدا کمپین ذخیره کن');if(!message)return;const history=p3.chats[id]||[];const memory=dmEl('dm-memory').value.slice(0,8000);p3.memories[id]=memory;p3save();const party=db.characters.map(h=>`${h.name} (${h.species} ${h.klass}, سطح ${h.level}, HP ${h.hp}, AC ${h.ac})`).join('؛ ');const story=p2.stories[id];const context=`تو Dungeon Master یک کمپین فانتزی رومیزی هستی. به فارسی روان روایت کن. انتخاب‌های بازیکن را محترم بشمار، برای آزمون‌ها نوع و DC پیشنهاد بده، ولی هیچ تاسی به جای بازیکن نینداز و هیچ نتیجه قطعی را پیش از دریافت نتیجه تاس اعلام نکن. اطلاعات محرمانه DM را بدون درخواست آشکار نکن. از قوانین D&D 5e فقط در حدی که مطمئنی استفاده کن. سناریو: ${JSON.stringify({title:c.title,genre:c.genre,setting:c.setting,hook:c.hook,twist:c.twist,notes:c.notes}).slice(0,4500)}. گروه: ${party.slice(0,1800)}. حافظه تاییدشده: ${memory}. ویرایشگر کمپین: ${JSON.stringify(story||{}).slice(0,4000)}. در پایان هر پاسخ در صورت مناسب بودن ۲ تا ۳ اقدام احتمالی پیشنهاد بده؛ بازیکن می‌تواند راه دیگری انتخاب کند.`;const messages=[{role:'system',content:context},...history.slice(-16).map(({role,content})=>({role,content})),{role:'user',content:message}];const btn=dmEl('dm-send');btn.disabled=true;btn.textContent='در حال روایت...';try{const r=await fetch(dmApi()+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:dmEl('dm-model').value,messages})});const data=await r.json();if(!r.ok)throw Error(data.detail||data.error||'خطای ارتباط');if(!data.message)throw Error('مدل پاسخی نداد');history.push({role:'user',content:message},{role:'assistant',content:data.message});p3.chats[id]=history.slice(-60);p3save();dmEl('dm-prompt').value='';dmLoad()}catch(err){dmEl('dm-status').textContent='خطا: '+String(err.message).slice(0,160)}finally{btn.disabled=false;btn.textContent='ارسال به DM ✦'}});
