'use strict';
/* Phase 2 is deliberately additive: the original MVP remains functional. */
const P2KEY='infinite-realms-phase2';
let p2;try{p2=JSON.parse(localStorage.getItem(P2KEY)||'{}')}catch{p2={}}
p2.sheets ||= {};p2.stories ||= {};p2.encounters ||= {};
const p2save=()=>localStorage.setItem(P2KEY,JSON.stringify(p2));
const skillMap={Acrobatics:'DEX','Animal Handling':'WIS',Arcana:'INT',Athletics:'STR',Deception:'CHA',History:'INT',Insight:'WIS',Intimidation:'CHA',Investigation:'INT',Medicine:'WIS',Nature:'INT',Perception:'WIS',Performance:'CHA',Persuasion:'CHA',Religion:'INT','Sleight of Hand':'DEX',Stealth:'DEX',Survival:'WIS'};
const classInfo={Fighter:{hit:10,saves:['STR','CON']},Wizard:{hit:6,saves:['INT','WIS']},Rogue:{hit:8,saves:['DEX','INT']},Cleric:{hit:8,saves:['WIS','CHA']},Paladin:{hit:10,saves:['WIS','CHA']},Ranger:{hit:10,saves:['STR','DEX']},Bard:{hit:8,saves:['DEX','CHA']},Barbarian:{hit:12,saves:['STR','CON']},Druid:{hit:8,saves:['INT','WIS']},Monk:{hit:8,saves:['STR','DEX']},Sorcerer:{hit:6,saves:['CON','CHA']},Warlock:{hit:8,saves:['WIS','CHA']}};
const prof=l=>Math.ceil(l/4)+1;
const roll20=(bonus=0,mode='normal')=>{const a=rnd(20),b=mode==='normal'?null:rnd(20),die=b===null?a:mode==='adv'?Math.max(a,b):Math.min(a,b);return {a,b,die,bonus,total:die+bonus,critical:die===20,fumble:die===1}};
const section=(title,html)=>`<div class="panel p2-panel"><h3>${title}</h3>${html}</div>`;
const field=(label,html)=>`<label>${label}${html}</label>`;
const p2host=document.createElement('section');p2host.id='rules';p2host.className='page';p2host.innerHTML=`<div class="section-head"><div><h2>موتور قوانین D&D</h2><p class="muted">محاسبات پایه مبتنی بر D&D 5e؛ جزئیات ویژگی‌های کلاس و تمام جادوها هنوز خودکار نیست.</p></div></div><div class="panel"><label>قهرمان فعال <select id="p2-hero"></select></label><div id="p2-sheet"></div></div><div class="p2-grid">${section('آزمون مهارت و نجات',`<div class="form-grid mini">${field('نوع آزمون','<select id="p2-check-type"><option value="skill">مهارت</option><option value="save">Saving Throw</option><option value="ability">ویژگی</option></select>')}${field('انتخاب','<select id="p2-check-name"></select>')}${field('DC','<input id="p2-dc" type="number" value="15" min="1" max="40">')}${field('حالت','<select id="p2-mode"><option value="normal">عادی</option><option value="adv">Advantage</option><option value="dis">Disadvantage</option></select>')}</div><button id="p2-check-roll" class="primary">انداختن D20</button><div id="p2-check-result" class="p2-result" aria-live="polite"></div>`)}${section('جادو و استراحت',`<p class="muted small">اسلات‌ها را بر اساس کلاس و سطح شخصیت تنظیم کن؛ جادوهای شناخته‌شده را DM مدیریت می‌کند.</p><div id="p2-spells"></div><div class="actions"><button id="p2-short-rest" class="outline">استراحت کوتاه</button><button id="p2-long-rest" class="primary">استراحت طولانی</button></div>`)}${section('حمله و آسیب',`<div class="form-grid mini">${field('پاداش حمله','<input type="number" id="p2-attack-bonus" value="5" min="-10" max="40">')}${field('AC هدف','<input type="number" id="p2-target-ac" value="13" min="1" max="40">')}${field('تاس آسیب','<select id="p2-damage-die"><option value="4">D4</option><option value="6">D6</option><option value="8" selected>D8</option><option value="10">D10</option><option value="12">D12</option></select>')}${field('تعداد تاس','<input type="number" id="p2-damage-count" value="1" min="1" max="12">')}${field('اصلاح‌کننده آسیب','<input type="number" id="p2-damage-mod" value="3" min="-20" max="40">')}${field('حالت حمله','<select id="p2-attack-mode"><option value="normal">عادی</option><option value="adv">Advantage</option><option value="dis">Disadvantage</option></select>')}</div><button class="primary" id="p2-attack">اجرای حمله</button><div id="p2-attack-result" class="p2-result" aria-live="polite"></div>`)}${section('راهنمای قوانین',`<p>در آزمون‌ها، برابری با DC موفقیت است. در حمله، ۲۰ طبیعی اصابت بحرانی و ۱ طبیعی خطاست. در اصابت بحرانی فقط تاس‌های آسیب دوبرابر می‌شوند، نه اصلاح‌کننده ثابت.</p><p class="muted small">این ابزار مرجع کامل قوانین رسمی نیست. مدیریت واکنش، Concentration، ویژگی‌های کلاس و افکت‌های پیچیده به عهده DM است.</p>`)}</div>`;
document.querySelector('main .page:last-of-type').after(p2host);
const nav=document.querySelector('#nav');const navBtn=document.createElement('button');navBtn.dataset.page='rules';navBtn.innerHTML='⚙ <span>قوانین پیشرفته</span>';nav.append(navBtn);pages.rules='موتور قوانین D&D';navBtn.addEventListener('click',()=>{go('rules');p2render()});
const p2Hero=()=>db.characters.find(c=>c.id===$('#p2-hero').value);
const p2sheet=c=>p2.sheets[c.id] ||= {skills:[],saves:classInfo[c.klass]?.saves||[],maxHp:c.hp,slots:[0,0,0,0,0,0,0,0,0],maxSlots:[0,0,0,0,0,0,0,0,0],conditions:[],notes:''};
function p2render(){const sel=$('#p2-hero'),prev=sel.value;sel.innerHTML=db.characters.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} — ${esc(c.klass)} ${c.level}</option>`).join('');if(db.characters.some(c=>c.id===prev))sel.value=prev;const c=p2Hero();if(!c){$('#p2-sheet').innerHTML='<p class="muted">ابتدا در بخش شخصیت‌ها یک قهرمان بساز.</p>';$('#p2-spells').innerHTML='';$('#p2-check-name').innerHTML='';return}const s=p2sheet(c);$('#p2-sheet').innerHTML=`<div class="card-meta"><span class="tag">${esc(c.species)}</span><span class="tag">${esc(c.klass)}</span><span class="tag">سطح ${c.level}</span><span class="tag">تسلط +${prof(c.level)}</span></div><div class="ability-pills">${abilities.map(a=>`<span>${a}<br><b>${c.abilities[a]} (${mod(c.abilities[a])>=0?'+':''}${mod(c.abilities[a])})</b></span>`).join('')}</div><div class="form-grid mini">${field('حداکثر HP',`<input type="number" id="p2-maxhp" min="1" max="1000" value="${s.maxHp}">`)}${field('HP فعلی',`<input type="number" id="p2-hp" min="0" max="1000" value="${c.hp}">`)}${field('AC',`<input type="number" id="p2-ac" min="1" max="40" value="${c.ac}">`)}${field('یادداشت شخصیت',`<input id="p2-hero-notes" maxlength="500" value="${esc(s.notes)}">`)}</div><h4>مهارت‌های مسلط</h4><div class="p2-checklist">${Object.entries(skillMap).map(([k,a])=>`<label><input type="checkbox" data-p2-skill="${k}" ${s.skills.includes(k)?'checked':''}> ${k} (${a})</label>`).join('')}</div><p class="muted small">Saving Throwهای پیش‌فرض کلاس: ${s.saves.join('، ')}</p><button class="primary" id="p2-save-sheet">ذخیره برگه پیشرفته</button>`;p2checks();p2spells();}
function p2checks(){const type=$('#p2-check-type').value;$('#p2-check-name').innerHTML=(type==='skill'?Object.keys(skillMap):abilities).map(x=>`<option>${x}</option>`).join('')}
function p2spells(){const c=p2Hero();if(!c)return;const s=p2sheet(c);$('#p2-spells').innerHTML=`<div class="p2-slots">${s.slots.map((n,i)=>`<label>سطح ${i+1}<input type="number" min="0" max="9" data-slot="${i}" value="${n}"><small>حداکثر <input type="number" min="0" max="9" data-maxslot="${i}" value="${s.maxSlots[i]}"></small></label>`).join('')}</div><p class="muted small">اسلات باقی‌مانده را با دکمه مصرف کاهش بده.</p><div class="actions">${s.slots.map((n,i)=>`<button class="outline" data-cast="${i}" ${n<=0?'disabled':''}>مصرف سطح ${i+1}</button>`).join('')}</div>`}
$('#p2-hero').addEventListener('change',p2render);$('#p2-check-type').addEventListener('change',p2checks);
$('#p2-sheet').addEventListener('click',e=>{if(e.target.id!=='p2-save-sheet')return;const c=p2Hero();if(!c)return;const s=p2sheet(c);s.skills=[...document.querySelectorAll('[data-p2-skill]:checked')].map(x=>x.dataset.p2Skill);s.maxHp=Math.max(1,Number($('#p2-maxhp').value)||1);c.hp=Math.max(0,Math.min(s.maxHp,Number($('#p2-hp').value)||0));c.ac=Math.max(1,Math.min(40,Number($('#p2-ac').value)||10));s.notes=$('#p2-hero-notes').value.slice(0,500);p2save();save();toast('برگه شخصیت ذخیره شد');p2render()});
$('#p2-check-roll').addEventListener('click',()=>{const c=p2Hero();if(!c)return toast('ابتدا قهرمان بساز');const s=p2sheet(c),type=$('#p2-check-type').value,name=$('#p2-check-name').value,ability=type==='skill'?skillMap[name]:name,bonus=mod(c.abilities[ability])+(type==='skill'&&s.skills.includes(name)||type==='save'&&s.saves.includes(name)?prof(c.level):0),dc=Number($('#p2-dc').value);if(!Number.isInteger(dc)||dc<1||dc>40)return toast('DC نامعتبر است');const r=roll20(bonus,$('#p2-mode').value);const ok=r.total>=dc;$('#p2-check-result').textContent=`${name}: ${r.a}${r.b===null?'':` / ${r.b}`} + (${bonus}) = ${r.total} در برابر DC ${dc} — ${ok?'موفق':'ناموفق'}`;db.rolls.unshift({id:uid(),n:20,count:1,m:bonus,mode:$('#p2-mode').value,rolls:[{value:r.die}],total:r.total,time:new Date().toLocaleString('fa-IR')});save()});
$('#p2-spells').addEventListener('change',e=>{const c=p2Hero();if(!c)return;const s=p2sheet(c),i=e.target.dataset.slot??e.target.dataset.maxslot;if(i===undefined)return;const n=Number(e.target.value);if(!Number.isInteger(n)||n<0||n>9){p2spells();return}if(e.target.dataset.maxslot!==undefined){s.maxSlots[i]=n;s.slots[i]=Math.min(s.slots[i],n)}else s.slots[i]=Math.min(n,s.maxSlots[i]);p2save();p2spells()});
$('#p2-spells').addEventListener('click',e=>{const i=e.target.dataset.cast;if(i===undefined)return;const c=p2Hero();if(!c)return;const s=p2sheet(c);if(s.slots[i]>0){s.slots[i]--;p2save();p2spells();toast('اسلات جادو مصرف شد')}});
$('#p2-short-rest').addEventListener('click',()=>toast('استراحت کوتاه ثبت شد؛ Hit Dice و ویژگی‌های کلاس را DM مدیریت کند'));
$('#p2-long-rest').addEventListener('click',()=>{const c=p2Hero();if(!c)return;const s=p2sheet(c);if(!confirm('استراحت طولانی انجام شود؟'))return;c.hp=s.maxHp;s.slots=[...s.maxSlots];p2save();save();p2render();toast('HP و اسلات‌های تنظیم‌شده بازیابی شدند')});
$('#p2-attack').addEventListener('click',()=>{const bonus=Number($('#p2-attack-bonus').value),ac=Number($('#p2-target-ac').value),die=Number($('#p2-damage-die').value),count=Number($('#p2-damage-count').value),dmod=Number($('#p2-damage-mod').value);if(![bonus,ac,die,count,dmod].every(Number.isInteger)||ac<1||ac>40||count<1||count>12||Math.abs(bonus)>40||Math.abs(dmod)>40)return toast('مقادیر حمله نامعتبر است');const r=roll20(bonus,$('#p2-attack-mode').value),hit=!r.fumble&&(r.critical||r.total>=ac),dice=hit?Array.from({length:count*(r.critical?2:1)},()=>rnd(die)):[],damage=hit?Math.max(0,dice.reduce((a,b)=>a+b,0)+dmod):0;$('#p2-attack-result').textContent=`D20: ${r.a}${r.b===null?'':` / ${r.b}`} + ${bonus} = ${r.total} | ${r.critical?'اصابت بحرانی':hit?'اصابت':'خطا'}${hit?` | آسیب ${dice.join('+')} ${dmod>=0?'+':''}${dmod} = ${damage}`:''}`});
/* A branching editor is attached to each saved campaign. It does not overwrite its generated narrative. */
const studio=document.createElement('section');studio.id='studio';studio.className='page';studio.innerHTML=`<div class="section-head"><div><h2>ویرایشگر کمپین</h2><p class="muted">صحنه‌ها، انتخاب‌ها، NPCها و وقایع جهان را برای هر کمپین مدیریت کن.</p></div></div><div class="panel"><label>کمپین <select id="p2-campaign"></select></label></div><div id="p2-studio-content"></div>`;
p2host.after(studio);const studioNav=document.createElement('button');studioNav.dataset.page='studio';studioNav.innerHTML='✎ <span>ویرایشگر کمپین</span>';nav.append(studioNav);pages.studio='ویرایشگر کمپین';studioNav.addEventListener('click',()=>{go('studio');p2studio()});
const currentCampaign=()=>db.campaigns.find(c=>c.id===$('#p2-campaign').value);
function story(c){return p2.stories[c.id] ||= {scenes:[{id:uid(),title:'آغاز ماجراجویی',body:c.hook,choices:[]}],npcs:[{id:uid(),name:c.ally[0],goal:c.ally[1],secret:''},{id:uid(),name:c.villain[0],goal:c.villain[1],secret:c.twist}],events:[]}}
function p2studio(){const sel=$('#p2-campaign'),old=sel.value;sel.innerHTML=db.campaigns.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('');if(db.campaigns.some(c=>c.id===old))sel.value=old;p2studioRender()}
function p2studioRender(){const c=currentCampaign();if(!c){$('#p2-studio-content').innerHTML='<div class="empty">ابتدا در سناریوساز یک کمپین تولید و ذخیره کن.</div>';return}const s=story(c);$('#p2-studio-content').innerHTML=`${section('صحنه‌های داستان',`<div class="p2-stack">${s.scenes.map((x,i)=>`<article class="p2-scene"><div class="section-head"><h4>${i+1}. ${esc(x.title)}</h4><button class="danger-outline" data-p2-delete-scene="${esc(x.id)}">حذف</button></div><p>${esc(x.body)}</p><div class="muted small">${x.choices.length?'انتخاب‌ها: '+x.choices.map(q=>esc(q.text)+' → '+esc(s.scenes.find(z=>z.id===q.next)?.title||'پایان')).join(' | '):'هنوز انتخابی تعریف نشده است.'}</div></article>`).join('')}</div><form id="p2-scene-form" class="form-grid">${field('عنوان صحنه','<input name="title" maxlength="100" required>')}${field('متن صحنه','<textarea name="body" maxlength="4000" required></textarea>')}<button class="primary">افزودن صحنه</button></form><hr><form id="p2-choice-form" class="form-grid">${field('از صحنه',`<select name="from">${s.scenes.map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`).join('')}</select>`)}${field('متن انتخاب','<input name="text" maxlength="250" required>')}${field('صحنه بعدی',`<select name="next"><option value="">پایان داستان</option>${s.scenes.map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`).join('')}</select>`)}<button class="primary">اتصال انتخاب</button></form>`)}${section('NPCها',`<div class="p2-stack">${s.npcs.map(n=>`<article class="p2-scene"><b>${esc(n.name)}</b><p>هدف: ${esc(n.goal)}</p><details><summary>راز DM</summary><p>${esc(n.secret||'ثبت نشده')}</p></details><button class="danger-outline" data-p2-delete-npc="${esc(n.id)}">حذف NPC</button></article>`).join('')}</div><form id="p2-npc-form" class="form-grid">${field('نام','<input name="name" required maxlength="80">')}${field('انگیزه','<input name="goal" required maxlength="250">')}${field('راز DM','<textarea name="secret" maxlength="800"></textarea>')}<button class="primary">افزودن NPC</button></form>`)}${section('وقایع و حافظه جهان',`<div class="p2-stack">${s.events.map(x=>`<article class="p2-scene"><small class="muted">${esc(x.date)}</small><p>${esc(x.text)}</p></article>`).join('')||'<p class="muted">هنوز اتفاقی ثبت نشده است.</p>'}</div><form id="p2-event-form">${field('تصمیم بازیکنان یا اتفاق مهم','<textarea name="text" maxlength="2000" required></textarea>')}<button class="primary">ثبت در تاریخچه جهان</button></form>`)}<div class="actions"><button id="p2-export-story" class="outline">↓ خروجی کمپین و داستان</button></div>`}
$('#p2-campaign').addEventListener('change',p2studioRender);
$('#p2-studio-content').addEventListener('submit',e=>{const c=currentCampaign();if(!c)return;const s=story(c),f=Object.fromEntries(new FormData(e.target));e.preventDefault();if(e.target.id==='p2-scene-form')s.scenes.push({id:uid(),title:f.title.trim(),body:f.body.trim(),choices:[]});else if(e.target.id==='p2-choice-form'){const from=s.scenes.find(x=>x.id===f.from);if(from)from.choices.push({id:uid(),text:f.text.trim(),next:f.next})}else if(e.target.id==='p2-npc-form')s.npcs.push({id:uid(),name:f.name.trim(),goal:f.goal.trim(),secret:f.secret.trim()});else if(e.target.id==='p2-event-form')s.events.unshift({id:uid(),text:f.text.trim(),date:new Date().toLocaleString('fa-IR')});else return;p2save();p2studioRender();toast('تغییرات کمپین ذخیره شد')});
$('#p2-studio-content').addEventListener('click',e=>{const c=currentCampaign();if(!c)return;const s=story(c),d=e.target.dataset;if(d.p2DeleteScene){if(s.scenes.length===1)return toast('حداقل یک صحنه لازم است');if(!confirm('این صحنه و مسیرهای منتهی به آن حذف شوند؟'))return;s.scenes=s.scenes.filter(x=>x.id!==d.p2DeleteScene);s.scenes.forEach(x=>x.choices=x.choices.filter(q=>q.next!==d.p2DeleteScene))}else if(d.p2DeleteNpc){s.npcs=s.npcs.filter(x=>x.id!==d.p2DeleteNpc)}else if(e.target.id==='p2-export-story'){download({version:2,campaign:c,story:s},'infinite-realms-story.json');return}else return;p2save();p2studioRender()});
/* Combat conditions and round log are layered on top of existing combat tracker. */
const conditionBox=document.createElement('div');conditionBox.className='panel';conditionBox.innerHTML=`<h3>وضعیت‌ها و رویدادهای مبارزه</h3><div class="form-grid mini"><label>مبارز <select id="p2-combat-unit"></select></label><label>وضعیت <select id="p2-condition">${['Blinded','Charmed','Deafened','Frightened','Grappled','Incapacitated','Invisible','Paralyzed','Petrified','Poisoned','Prone','Restrained','Stunned','Unconscious','Exhaustion'].map(x=>`<option>${x}</option>`).join('')}</select></label></div><button id="p2-add-condition" class="primary">افزودن / برداشتن وضعیت</button><div id="p2-condition-list"></div>`;
$('#combat-list').closest('.panel').after(conditionBox);
function p2combat(){const sel=$('#p2-combat-unit'),old=sel.value;sel.innerHTML=db.combat.units.map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join('');if(db.combat.units.some(u=>u.id===old))sel.value=old;$('#p2-condition-list').innerHTML=db.combat.units.map(u=>`<p><b>${esc(u.name)}:</b> ${esc((u.conditions||[]).join('، ')||'بدون وضعیت')}</p>`).join('')||'<p class="muted">مبارزی وجود ندارد.</p>'}
$('#p2-add-condition').addEventListener('click',()=>{const u=db.combat.units.find(x=>x.id===$('#p2-combat-unit').value);if(!u)return toast('مبارزی انتخاب نشده');u.conditions ||= [];const x=$('#p2-condition').value;u.conditions=u.conditions.includes(x)?u.conditions.filter(y=>y!==x):[...u.conditions,x];save();p2combat()});
const originalCombat=renderCombat;renderCombat=function(){originalCombat();p2combat()};
/* Saved campaigns and character updates are reflected when these sections are opened. */
const originalGo=go;go=function(page){originalGo(page);if(page==='rules')p2render();if(page==='studio')p2studio()};
